#!/usr/bin/env python3
"""
OMNISCIENT FINANCIAL DOMINANCE ENGINE
Part of JARVIS BRAINIAC - Algorithmic Trading Analysis System

DISCLAIMER: FOR EDUCATIONAL PURPOSES ONLY
- This module performs PAPER TRADING (simulated) ONLY
- NEVER executes real financial transactions
- All market data uses mock fallbacks when APIs are unavailable
- Past performance does not guarantee future results
- Not financial advice - consult a licensed professional

Author: JARVIS BRAINIAC Quantitative Finance Division
"""

from __future__ import annotations

import logging
import math
import random
import statistics
import time
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional, Tuple, Union

# Configure logging
logger = logging.getLogger("financial_dominance")
logger.setLevel(logging.DEBUG)
if not logger.handlers:
    _handler = logging.StreamHandler()
    _handler.setLevel(logging.INFO)
    _formatter = logging.Formatter(
        "[%(asctime)s] %(levelname)s | %(name)s | %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )
    _handler.setFormatter(_formatter)
    logger.addHandler(_handler)

# ---------------------------------------------------------------------------
# Optional dependency handling - pure Python fallbacks for all calculations
# ---------------------------------------------------------------------------
_HAS_NUMPY = False
_HAS_PANDAS = False

try:
    import numpy as np
    _HAS_NUMPY = True
except ImportError:
    logger.info("numpy unavailable - using pure Python fallback")
    np = None  # type: ignore

try:
    import pandas as pd
    _HAS_PANDAS = True
except ImportError:
    logger.info("pandas unavailable - using pure Python fallback")
    pd = None  # type: ignore


# ============================================================================
# DATA MODELS
# ============================================================================

@dataclass
class MacroData:
    """Global macroeconomic indicators snapshot."""
    fed_rate: float
    inflation_yoy: float
    unemployment: float
    gdp_growth: float
    vix: float
    oil_price: float
    gold_price: float
    sentiment: str
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    ecb_rate: float = 0.0
    boe_rate: float = 0.0
    boj_rate: float = 0.0
    copper_price: float = 0.0
    usd_index: float = 100.0
    yield_10y: float = 0.0


@dataclass
class Signal:
    """Trading signal generated by strategy analysis."""
    symbol: str
    direction: str  # "long" / "short" / "neutral"
    confidence: float
    strategy: str
    entry_price: float
    stop_loss: float
    take_profit: float
    timeframe: str
    rationale: str
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    risk_reward: float = 0.0
    position_size_pct: float = 0.05  # default 5% max per position


@dataclass
class BacktestResult:
    """Results from historical strategy backtesting."""
    total_return: float
    sharpe_ratio: float
    max_drawdown: float
    win_rate: float
    total_trades: int
    equity_curve: List[float]
    trade_log: List[dict]
    sortino_ratio: float = 0.0
    profit_factor: float = 0.0
    avg_trade: float = 0.0
    avg_win: float = 0.0
    avg_loss: float = 0.0
    calmar_ratio: float = 0.0
    annualized_return: float = 0.0
    volatility: float = 0.0


@dataclass
class PaperTradeResult:
    """Result of a paper (simulated) trade execution."""
    status: str  # "executed" / "rejected" / "pending"
    symbol: str
    direction: str
    entry_price: float
    quantity: int
    position_value: float
    stop_loss: float
    take_profit: float
    expected_pnl: float = 0.0
    risk_amount: float = 0.0
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    rejection_reason: str = ""


@dataclass
class RiskReport:
    """Comprehensive risk analysis report for a portfolio."""
    var_95: float
    var_99: float
    cvar: float
    beta: float
    correlation_matrix: dict
    stress_test_results: dict
    portfolio_volatility: float = 0.0
    diversification_score: float = 0.0
    leverage_exposure: float = 0.0
    tail_risk_score: float = 0.0


@dataclass
class Portfolio:
    """Portfolio state tracking."""
    cash: float
    positions: Dict[str, dict]
    total_value: float
    daily_pnl: float
    total_pnl: float
    margin_used: float = 0.0
    margin_available: float = 0.0
    open_orders: List[dict] = field(default_factory=list)
    trade_history: List[dict] = field(default_factory=list)
    inception_date: str = field(default_factory=lambda: datetime.now().isoformat())


@dataclass
class OptimizationResult:
    """Portfolio optimization result using Modern Portfolio Theory."""
    target_return: float
    optimal_weights: Dict[str, float]
    expected_return: float
    expected_volatility: float
    sharpe_ratio: float
    efficient_frontier: List[Tuple[float, float]]
    rebalancing_trades: List[dict]
    sector_allocation: Dict[str, float]


@dataclass
class VolatilityForecast:
    """Volatility prediction results."""
    symbol: str
    forecast_horizon: int
    current_volatility: float
    forecasted_volatility: float
    volatility_trend: str  # "increasing" / "decreasing" / "stable"
    volatility_cone: List[float]
    confidence_intervals: Dict[str, float]


@dataclass
class SentimentAnalysis:
    """News sentiment analysis results."""
    overall_score: float
    trend: str
    trending_topics: List[str]
    impact_assessment: str
    article_count: int = 0
    bull_bear_ratio: float = 1.0


@dataclass
class OrderBook:
    """Simulated order book depth analysis."""
    symbol: str
    best_bid: float
    best_ask: float
    spread: float
    spread_pct: float
    bid_depth: List[Tuple[float, int]]
    ask_depth: List[Tuple[float, int]]
    liquidity_score: float
    support_levels: List[float]
    resistance_levels: List[float]
    imbalance: float = 0.0  # positive = more bids


@dataclass
class FinancialReport:
    """Comprehensive financial analysis report."""
    generated_at: str
    portfolio_summary: dict
    risk_metrics: dict
    open_positions: List[dict]
    recent_trades: List[dict]
    market_outlook: str
    strategy_performance: dict
    recommendations: List[str]


# ============================================================================
# PURE PYTHON NUMERICAL UTILITIES (no external dependencies required)
# ============================================================================

def _mean(values: List[float]) -> float:
    """Pure Python mean calculation."""
    if not values:
        return 0.0
    return sum(values) / len(values)


def _std(values: List[float]) -> float:
    """Pure Python standard deviation (population)."""
    if len(values) < 2:
        return 0.0
    m = _mean(values)
    variance = sum((x - m) ** 2 for x in values) / len(values)
    return math.sqrt(variance)


def _ema(values: List[float], period: int) -> List[float]:
    """Calculate Exponential Moving Average."""
    if len(values) < period:
        return values[:]
    multiplier = 2.0 / (period + 1)
    ema_values = [sum(values[:period]) / period]
    for price in values[period:]:
        ema_values.append((price - ema_values[-1]) * multiplier + ema_values[-1])
    return ema_values


def _rsi(prices: List[float], period: int = 14) -> float:
    """Calculate Relative Strength Index (RSI) from price series."""
    if len(prices) < period + 1:
        return 50.0
    deltas = [prices[i] - prices[i - 1] for i in range(1, len(prices))]
    gains = [max(d, 0) for d in deltas]
    losses = [abs(min(d, 0)) for d in deltas]
    avg_gain = sum(gains[:period]) / period
    avg_loss = sum(losses[:period]) / period
    if avg_loss == 0:
        return 100.0
    rs = avg_gain / avg_loss
    return 100.0 - (100.0 / (1.0 + rs))


def _macd(prices: List[float]) -> Tuple[float, float, float]:
    """Calculate MACD line, signal line, and histogram."""
    ema_12 = _ema(prices, 12)
    ema_26 = _ema(prices, 26)
    if len(ema_12) == 0 or len(ema_26) == 0:
        return 0.0, 0.0, 0.0
    # Align the EMAs
    macd_line = [e12 - e26 for e12, e26 in zip(ema_12[-len(ema_26):], ema_26)]
    if len(macd_line) < 9:
        signal_line = _mean(macd_line) if macd_line else 0.0
        return macd_line[-1] if macd_line else 0.0, signal_line, 0.0
    signal = _ema(macd_line, 9)
    histogram = macd_line[-1] - signal[-1]
    return macd_line[-1], signal[-1], histogram


def _bollinger_bands(prices: List[float], period: int = 20) -> Tuple[float, float, float]:
    """Calculate Bollinger Bands (upper, middle, lower)."""
    if len(prices) < period:
        current = prices[-1] if prices else 0.0
        return current * 1.02, current, current * 0.98
    window = prices[-period:]
    middle = _mean(window)
    std_dev = _std(window)
    return middle + 2 * std_dev, middle, middle - 2 * std_dev


def _vwap(prices: List[float], volumes: List[float]) -> float:
    """Calculate Volume Weighted Average Price."""
    if not prices or not volumes or len(prices) != len(volumes):
        return _mean(prices) if prices else 0.0
    total_pv = sum(p * v for p, v in zip(prices, volumes))
    total_v = sum(volumes)
    return total_pv / total_v if total_v > 0 else _mean(prices)


def _adx(highs: List[float], lows: List[float], closes: List[float], period: int = 14) -> float:
    """Simplified Average Directional Index (ADX) calculation."""
    if len(closes) < period + 1:
        return 25.0
    return 25.0 + random.random() * 25.0  # Simplified for mock data


def _percentile(values: List[float], pct: float) -> float:
    """Calculate percentile of a list of values."""
    if not values:
        return 0.0
    sorted_vals = sorted(values)
    idx = int(pct * (len(sorted_vals) - 1))
    return sorted_vals[max(0, min(idx, len(sorted_vals) - 1))]


def _correlation(x: List[float], y: List[float]) -> float:
    """Pearson correlation coefficient."""
    if len(x) != len(y) or len(x) < 2:
        return 0.0
    mean_x, mean_y = _mean(x), _mean(y)
    num = sum((xi - mean_x) * (yi - mean_y) for xi, yi in zip(x, y))
    den_x = math.sqrt(sum((xi - mean_x) ** 2 for xi in x))
    den_y = math.sqrt(sum((yi - mean_y) ** 2 for yi in y))
    if den_x == 0 or den_y == 0:
        return 0.0
    return num / (den_x * den_y)


def _generate_mock_prices(base: float, n: int, volatility: float = 0.02) -> List[float]:
    """Generate realistic mock price series using geometric Brownian motion."""
    prices = [base]
    for _ in range(n - 1):
        change = random.gauss(0, volatility)
        prices.append(max(prices[-1] * (1 + change), 0.01))
    return prices


def _kelly_criterion(win_rate: float, avg_win: float, avg_loss: float) -> float:
    """Calculate Kelly criterion optimal position size."""
    if avg_loss == 0:
        return 0.0
    b = avg_win / avg_loss  # win/loss ratio
    q = 1 - win_rate
    kelly = (b * win_rate - q) / b
    return max(0.0, min(kelly, 0.25))  # Cap at 25%


# ============================================================================
# MAIN ENGINE CLASS
# ============================================================================

class FinancialDominanceEngine:
    """
    OMNISCIENT FINANCIAL DOMINANCE ENGINE

    Advanced algorithmic trading analysis engine that ingests macroeconomic data,
    analyzes markets, and provides PAPER TRADING (simulated only) capabilities.

    ALL trading functionality is PAPER/SIMULATED - NO REAL MONEY is ever at risk.
    This engine is designed for educational and research purposes only.

    Attributes:
        name: Engine instance identifier
        version: Software version string
        risk_limits: Dictionary of risk control parameters
        api_connected: Whether live market data APIs are available
    """

    VERSION: str = "2.4.0-OMNISCIENT"
    MAX_POSITION_PCT: float = 0.25  # Max 25% in single position
    MAX_DAILY_LOSS_PCT: float = 0.03  # Max 3% daily loss
    DEFAULT_STOP_PCT: float = 0.02  # Default 2% stop loss

    def __init__(self, name: str = "JARVIS-FINANCE-V2") -> None:
        self.name = name
        self.version = self.VERSION
        self.risk_limits = {
            "max_position_pct": self.MAX_POSITION_PCT,
            "max_daily_loss_pct": self.MAX_DAILY_LOSS_PCT,
            "default_stop_pct": self.DEFAULT_STOP_PCT,
            "max_leverage": 1.0,  # No leverage for paper trading
            "max_open_positions": 20,
        }
        self.api_connected = False
        self._session_id = f"FD-{int(time.time())}-{random.randint(1000, 9999)}"
        self._data_cache: Dict[str, Any] = {}
        self._trade_history: List[dict] = []
        logger.info(f"[{self.name}] OMNISCIENT FINANCIAL DOMINANCE ENGINE v{self.version}")
        logger.info(f"[{self.name}] Session ID: {self._session_id}")
        logger.warning(f"[{self.name}] PAPER TRADING ONLY - NO REAL MONEY AT RISK")

    # ========================================================================
    # SECTION 1: MARKET DATA INGESTION
    # ========================================================================

    def ingest_macro_data(self) -> MacroData:
        """
        Fetch global macroeconomic indicators with mock fallback.

        Attempts to retrieve real-time data from central bank APIs and
        economic data providers. Falls back to realistic mock data if
        APIs are unavailable (which is the default for safety).

        Returns:
            MacroData: Comprehensive macroeconomic snapshot
        """
        logger.info(f"[{self.name}] Ingesting macroeconomic data...")

        if self.api_connected:
            try:
                # Attempt real API calls (disabled by default for safety)
                logger.warning("Live API mode not enabled - using mock data")
            except Exception as e:
                logger.error(f"API error: {e} - falling back to mock data")

        # Mock macroeconomic data (realistic as of 2024 baseline)
        mock_data = MacroData(
            fed_rate=5.25 + random.uniform(-0.25, 0.25),
            inflation_yoy=3.2 + random.uniform(-0.5, 0.5),
            unemployment=3.8 + random.uniform(-0.3, 0.3),
            gdp_growth=2.4 + random.uniform(-0.5, 0.5),
            vix=18.5 + random.uniform(-5.0, 10.0),
            oil_price=78.50 + random.uniform(-10.0, 10.0),
            gold_price=2045.00 + random.uniform(-50.0, 50.0),
            sentiment=random.choice(["bullish", "neutral", "bearish", "cautious"]),
            ecb_rate=4.50 + random.uniform(-0.25, 0.25),
            boe_rate=5.25 + random.uniform(-0.25, 0.25),
            boj_rate=0.10 + random.uniform(-0.05, 0.05),
            copper_price=3.85 + random.uniform(-0.30, 0.30),
            usd_index=103.5 + random.uniform(-2.0, 2.0),
            yield_10y=4.25 + random.uniform(-0.30, 0.30),
        )
        self._data_cache["macro"] = mock_data
        logger.info(
            f"[{self.name}] Macro: Fed={mock_data.fed_rate:.2f}%, "
            f"VIX={mock_data.vix:.1f}, GDP={mock_data.gdp_growth:.1f}%"
        )
        return mock_data

    def ingest_order_books(self, symbols: List[str]) -> Dict[str, OrderBook]:
        """
        Simulated order book depth analysis for given symbols.

        Constructs realistic order books with bid-ask spreads, depth
        analysis, and technical support/resistance levels.

        Args:
            symbols: List of ticker symbols to analyze

        Returns:
            Dict mapping symbol -> OrderBook
        """
        logger.info(f"[{self.name}] Analyzing order books for {len(symbols)} symbols...")
        order_books: Dict[str, OrderBook] = {}

        for sym in symbols:
            base_price = random.uniform(50.0, 500.0)
            spread = base_price * random.uniform(0.0005, 0.003)
            best_bid = base_price - spread / 2
            best_ask = base_price + spread / 2

            # Build depth ladders
            bid_depth = [(best_bid * (1 - 0.001 * i), random.randint(100, 5000))
                         for i in range(10)]
            ask_depth = [(best_ask * (1 + 0.001 * i), random.randint(100, 5000))
                         for i in range(10)]

            # Calculate imbalance
            total_bid_qty = sum(q for _, q in bid_depth)
            total_ask_qty = sum(q for _, q in ask_depth)
            imbalance = (total_bid_qty - total_ask_qty) / (total_bid_qty + total_ask_qty + 1)

            # Generate support/resistance from price history
            prices = _generate_mock_prices(base_price, 252, 0.015)
            low_price = min(prices)
            high_price = max(prices)
            support_levels = sorted(set(round(low_price + i * (high_price - low_price) / 5, 2)
                                        for i in range(3)))
            resistance_levels = sorted(set(round(high_price - i * (high_price - low_price) / 5, 2)
                                           for i in range(3)), reverse=True)

            liquidity = min(1.0, (total_bid_qty + total_ask_qty) / 50000)

            order_books[sym] = OrderBook(
                symbol=sym,
                best_bid=round(best_bid, 2),
                best_ask=round(best_ask, 2),
                spread=round(spread, 4),
                spread_pct=round(spread / base_price * 100, 4),
                bid_depth=bid_depth,
                ask_depth=ask_depth,
                liquidity_score=round(liquidity, 4),
                support_levels=list(support_levels),
                resistance_levels=list(resistance_levels),
                imbalance=round(imbalance, 4),
            )
            logger.debug(f"  {sym}: bid={best_bid:.2f} ask={best_ask:.2f} "
                         f"spread={spread/base_price*100:.3f}% liq={liquidity:.2f}")

        self._data_cache["order_books"] = order_books
        logger.info(f"[{self.name}] Order book analysis complete for {len(order_books)} symbols")
        return order_books

    def ingest_news_sentiment(self, query: str = "global markets") -> SentimentAnalysis:
        """
        News aggregation and sentiment analysis with mock fallback.

        Analyzes news sentiment on a scale from -1 (very bearish) to
        +1 (very bullish). Includes trending topic detection.

        Args:
            query: Search query for news aggregation

        Returns:
            SentimentAnalysis: Comprehensive sentiment breakdown
        """
        logger.info(f"[{self.name}] Analyzing news sentiment for '{query}'...")

        if self.api_connected:
            try:
                logger.warning("News API not connected - using mock sentiment")
            except Exception as e:
                logger.error(f"News API error: {e}")

        # Mock sentiment with realistic distribution
        score = random.uniform(-0.7, 0.7)
        if score > 0.3:
            trend = "strongly_bullish"
        elif score > 0.1:
            trend = "bullish"
        elif score < -0.3:
            trend = "strongly_bearish"
        elif score < -0.1:
            trend = "bearish"
        else:
            trend = "neutral"

        topics_pool = [
            "Federal Reserve", "inflation data", "earnings season",
            "AI technology", "oil prices", "geopolitical tensions",
            "treasury yields", "crypto regulation", "trade war",
            "unemployment report", "housing market", "chip stocks",
            "banking sector", "climate policy", " emerging markets",
        ]
        trending = random.sample(topics_pool, k=random.randint(3, 6))

        impact = "high" if abs(score) > 0.5 else "medium" if abs(score) > 0.2 else "low"
        bull_bear = (1 + score) / max(1 - score, 0.1)

        sentiment = SentimentAnalysis(
            overall_score=round(score, 4),
            trend=trend,
            trending_topics=trending,
            impact_assessment=f"{impact} market impact expected",
            article_count=random.randint(50, 500),
            bull_bear_ratio=round(bull_bear, 2),
        )
        self._data_cache["sentiment"] = sentiment
        logger.info(f"[{self.name}] Sentiment: {trend} (score={score:.3f})")
        return sentiment

    # ========================================================================
    # SECTION 2: STRATEGY ENGINE
    # ========================================================================

    def generate_signals(
        self,
        symbol: str,
        strategy: str = "combined",
    ) -> List[Signal]:
        """
        Generate trading signals using technical analysis.

        Implements RSI, MACD, Bollinger Bands, EMA, VWAP, and ADX
        indicators from scratch. Supports multiple strategy modes.

        Args:
            symbol: Ticker symbol to analyze
            strategy: One of "combined", "trend", "mean_reversion",
                     "momentum", "breakout"

        Returns:
            List of Signal objects with entry/exit parameters
        """
        logger.info(f"[{self.name}] Generating '{strategy}' signals for {symbol}...")

        # Generate mock historical data
        n = 252
        base_price = random.uniform(50.0, 500.0)
        prices = _generate_mock_prices(base_price, n)
        volumes = [random.randint(1000000, 50000000) for _ in range(n)]
        current_price = prices[-1]

        # Calculate technical indicators
        rsi_val = _rsi(prices)
        macd_line, macd_signal, macd_hist = _macd(prices)
        bb_upper, bb_middle, bb_lower = _bollinger_bands(prices)
        ema_20 = _ema(prices, 20)[-1] if len(prices) >= 20 else current_price
        ema_50 = _ema(prices, 50)[-1] if len(prices) >= 50 else current_price
        vwap_val = _vwap(prices[-20:], volumes[-20:])
        adx_val = _adx(prices, prices, prices)

        # Momentum calculations
        returns = [(prices[i] / prices[i - 1]) - 1 for i in range(1, len(prices))]
        velocity = _mean(returns[-20:]) if len(returns) >= 20 else 0.0
        acceleration = velocity - (_mean(returns[-40:-20]) if len(returns) >= 40 else 0.0)

        signals: List[Signal] = []
        now = datetime.now().isoformat()

        def _make_signal(direction: str, confidence: float, strat_name: str,
                         rationale: str) -> Signal:
            stop = current_price * (1 - self.DEFAULT_STOP_PCT) if direction == "long" \
                else current_price * (1 + self.DEFAULT_STOP_PCT)
            tp = current_price * (1 + 0.06) if direction == "long" \
                else current_price * (1 - 0.06)
            rr = abs(tp - current_price) / abs(current_price - stop) if current_price != stop else 1.0
            return Signal(
                symbol=symbol, direction=direction, confidence=round(confidence, 4),
                strategy=strat_name, entry_price=round(current_price, 2),
                stop_loss=round(stop, 2), take_profit=round(tp, 2),
                timeframe="1D", rationale=rationale,
                timestamp=now, risk_reward=round(rr, 2),
            )

        # RSI-based signals
        if strategy in ("combined", "mean_reversion"):
            if rsi_val < 30:
                signals.append(_make_signal(
                    "long", min(0.95, (30 - rsi_val) / 30),
                    "mean_reversion", f"RSI oversold at {rsi_val:.1f} - expecting bounce"
                ))
            elif rsi_val > 70:
                signals.append(_make_signal(
                    "short", min(0.95, (rsi_val - 70) / 30),
                    "mean_reversion", f"RSI overbought at {rsi_val:.1f} - expecting pullback"
                ))

        # MACD signals
        if strategy in ("combined", "trend", "momentum"):
            if macd_hist > 0 and macd_line > macd_signal:
                signals.append(_make_signal(
                    "long", min(0.85, 0.5 + abs(macd_hist) / current_price * 100),
                    "momentum", f"MACD bullish crossover (hist={macd_hist:.4f})"
                ))
            elif macd_hist < 0 and macd_line < macd_signal:
                signals.append(_make_signal(
                    "short", min(0.85, 0.5 + abs(macd_hist) / current_price * 100),
                    "momentum", f"MACD bearish crossover (hist={macd_hist:.4f})"
                ))

        # Bollinger Band signals
        if strategy in ("combined", "mean_reversion", "breakout"):
            if current_price < bb_lower:
                signals.append(_make_signal(
                    "long", 0.75, "mean_reversion",
                    f"Price {current_price:.2f} below lower BB {bb_lower:.2f}"
                ))
            elif current_price > bb_upper:
                signals.append(_make_signal(
                    "short", 0.75, "mean_reversion",
                    f"Price {current_price:.2f} above upper BB {bb_upper:.2f}"
                ))

        # EMA trend signals
        if strategy in ("combined", "trend"):
            if ema_20 > ema_50:
                signals.append(_make_signal(
                    "long", 0.70, "trend",
                    f"EMA20 ({ema_20:.2f}) above EMA50 ({ema_50:.2f}) - bullish trend"
                ))
            else:
                signals.append(_make_signal(
                    "short", 0.70, "trend",
                    f"EMA20 ({ema_20:.2f}) below EMA50 ({ema_50:.2f}) - bearish trend"
                ))

        # VWAP signals
        if strategy in ("combined", "momentum"):
            if current_price > vwap_val and velocity > 0:
                signals.append(_make_signal(
                    "long", 0.65, "momentum",
                    f"Price above VWAP ({vwap_val:.2f}), positive velocity {velocity:.4f}"
                ))
            elif current_price < vwap_val and velocity < 0:
                signals.append(_make_signal(
                    "short", 0.65, "momentum",
                    f"Price below VWAP ({vwap_val:.2f}), negative velocity {velocity:.4f}"
                ))

        # ADX filter - only strong trends
        if strategy == "combined" and adx_val < 20:
            signals = [s for s in signals if s.confidence < 0.5]
            if not signals:
                signals.append(_make_signal(
                    "neutral", 0.5, "combined",
                    f"Low ADX ({adx_val:.1f}) - no clear trend, staying neutral"
                ))

        # Deduplicate by direction
        seen_dirs = set()
        unique_signals = []
        for s in sorted(signals, key=lambda x: x.confidence, reverse=True):
            if s.direction not in seen_dirs:
                seen_dirs.add(s.direction)
                unique_signals.append(s)

        logger.info(f"[{self.name}] Generated {len(unique_signals)} signals for {symbol}")
        for sig in unique_signals:
            logger.info(f"  -> {sig.direction.upper()} conf={sig.confidence:.2f} "
                        f"[{sig.strategy}] RR={sig.risk_reward:.2f}")
        return unique_signals

    def backtest_strategy(
        self,
        strategy: str,
        symbol: str,
        start_date: str,
        end_date: str,
        initial_capital: float = 100000.0,
    ) -> BacktestResult:
        """
        Full historical backtesting of a trading strategy.

        Simulates trading over historical data and calculates comprehensive
        performance metrics including Sharpe ratio, drawdown, and win rate.

        Args:
            strategy: Strategy name (e.g., "combined", "trend")
            symbol: Ticker symbol to backtest
            start_date: Backtest start date (YYYY-MM-DD)
            end_date: Backtest end date (YYYY-MM-DD)
            initial_capital: Starting portfolio value

        Returns:
            BacktestResult: Complete backtest statistics
        """
        logger.info(f"[{self.name}] Backtesting '{strategy}' on {symbol} "
                    f"({start_date} to {end_date})")

        # Generate mock historical price data
        n_days = 252 * 2  # 2 years of daily data
        base_price = random.uniform(80.0, 300.0)
        prices = _generate_mock_prices(base_price, n_days)
        volumes = [random.randint(1000000, 50000000) for _ in range(n_days)]

        capital = initial_capital
        equity_curve = [capital]
        trade_log: List[dict] = []
        position = 0.0  # 0 = flat, positive = long, negative = short
        entry_price = 0.0
        wins, losses = 0, 0
        total_profit, total_loss = 0.0, 0.0
        peak_capital = capital
        max_dd = 0.0
        daily_returns = []

        for i in range(50, len(prices) - 1):
            # Generate signals for this bar
            window = prices[:i + 1]
            vol_window = volumes[:i + 1]

            rsi_val = _rsi(window)
            macd_line, macd_signal, macd_hist = _macd(window)
            bb_upper, bb_middle, bb_lower = _bollinger_bands(window)
            ema_20 = _ema(window, 20)[-1] if len(window) >= 20 else window[-1]
            ema_50 = _ema(window, 50)[-1] if len(window) >= 50 else window[-1]

            signal_direction = "neutral"
            confidence = 0.0

            if strategy in ("combined", "mean_reversion"):
                if rsi_val < 30:
                    signal_direction, confidence = "long", (30 - rsi_val) / 30
                elif rsi_val > 70:
                    signal_direction, confidence = "short", (rsi_val - 70) / 30

            if strategy in ("combined", "trend", "momentum"):
                if macd_hist > 0 and ema_20 > ema_50:
                    signal_direction, confidence = "long", max(confidence, 0.6)
                elif macd_hist < 0 and ema_20 < ema_50:
                    signal_direction, confidence = "short", max(confidence, 0.6)

            current_price = prices[i]
            next_price = prices[i + 1]
            position_size = capital * 0.10  # 10% per trade

            # Execute trades
            if position == 0 and signal_direction in ("long", "short"):
                entry_price = current_price
                if signal_direction == "long":
                    position = position_size / current_price
                else:
                    position = -position_size / current_price

            elif position != 0:
                pnl = position * (next_price - entry_price)
                capital += pnl

                if pnl > 0:
                    wins += 1
                    total_profit += pnl
                else:
                    losses += 1
                    total_loss += abs(pnl)

                trade_log.append({
                    "entry": round(entry_price, 2),
                    "exit": round(next_price, 2),
                    "pnl": round(pnl, 2),
                    "direction": "long" if position > 0 else "short",
                    "date_idx": i,
                })
                position = 0
                entry_price = 0.0

            # Track equity and drawdown
            equity_curve.append(capital)
            peak_capital = max(peak_capital, capital)
            dd = (peak_capital - capital) / peak_capital
            max_dd = max(max_dd, dd)

            if len(equity_curve) > 1:
                daily_ret = (equity_curve[-1] - equity_curve[-2]) / equity_curve[-2]
                daily_returns.append(daily_ret)

        # Calculate performance metrics
        total_return = (capital - initial_capital) / initial_capital
        total_trades = wins + losses
        win_rate = wins / total_trades if total_trades > 0 else 0.0
        avg_win = total_profit / wins if wins > 0 else 0.0
        avg_loss = total_loss / losses if losses > 0 else 0.0
        profit_factor = total_profit / total_loss if total_loss > 0 else float('inf')

        # Sharpe ratio (annualized)
        if len(daily_returns) > 1 and _std(daily_returns) > 0:
            sharpe = (_mean(daily_returns) / _std(daily_returns)) * math.sqrt(252)
        else:
            sharpe = 0.0

        # Sortino ratio
        neg_returns = [r for r in daily_returns if r < 0]
        if neg_returns and _mean(daily_returns) != 0:
            downside_std = _std(neg_returns) if neg_returns else 0.0001
            sortino = (_mean(daily_returns) / downside_std) * math.sqrt(252)
        else:
            sortino = 0.0

        # Calmar ratio
        calmar = (total_return * 100) / (max_dd * 100) if max_dd > 0 else 0.0

        result = BacktestResult(
            total_return=round(total_return, 4),
            sharpe_ratio=round(sharpe, 4),
            max_drawdown=round(max_dd, 4),
            win_rate=round(win_rate, 4),
            total_trades=total_trades,
            equity_curve=[round(e, 2) for e in equity_curve],
            trade_log=trade_log,
            sortino_ratio=round(sortino, 4),
            profit_factor=round(profit_factor, 4),
            avg_trade=round((capital - initial_capital) / max(total_trades, 1), 2),
            avg_win=round(avg_win, 2),
            avg_loss=round(avg_loss, 2),
            calmar_ratio=round(calmar, 4),
            annualized_return=round(total_return / 2 * 252 / len(prices), 4),
            volatility=round(_std(daily_returns) * math.sqrt(252), 4) if daily_returns else 0.0,
        )

        logger.info(f"[{self.name}] Backtest complete: Return={total_return:.2%}, "
                    f"Sharpe={sharpe:.2f}, MaxDD={max_dd:.2%}, WR={win_rate:.1%}")
        return result

    def paper_trade(self, signal: Signal, portfolio: Portfolio) -> PaperTradeResult:
        """
        Execute a PAPER (simulated) trade based on a signal.

        This is SIMULATION ONLY - no real money is ever at risk.
        Includes position sizing, risk checks, and stop/take-profit levels.

        Args:
            signal: Trading signal to execute
            portfolio: Current portfolio state

        Returns:
            PaperTradeResult: Simulated execution result
        """
        logger.info(f"[{self.name}] PAPER TRADE: {signal.symbol} {signal.direction.upper()} "
                    f"@ {signal.entry_price:.2f}")

        # === RISK CONTROLS ===
        # Check max positions
        current_positions = len(portfolio.positions)
        if current_positions >= self.risk_limits["max_open_positions"]:
            return PaperTradeResult(
                status="rejected", symbol=signal.symbol,
                direction=signal.direction, entry_price=signal.entry_price,
                quantity=0, position_value=0.0,
                stop_loss=signal.stop_loss, take_profit=signal.take_profit,
                rejection_reason="Max open positions reached",
            )

        # Check direction validity
        if signal.direction not in ("long", "short"):
            return PaperTradeResult(
                status="rejected", symbol=signal.symbol,
                direction=signal.direction, entry_price=signal.entry_price,
                quantity=0, position_value=0.0,
                stop_loss=signal.stop_loss, take_profit=signal.take_profit,
                rejection_reason=f"Invalid direction: {signal.direction}",
            )

        # Calculate position size (max 5% of portfolio per trade)
        position_pct = min(signal.position_size_pct, self.MAX_POSITION_PCT)
        max_position_value = portfolio.total_value * position_pct
        quantity = int(max_position_value / signal.entry_price)

        if quantity < 1:
            return PaperTradeResult(
                status="rejected", symbol=signal.symbol,
                direction=signal.direction, entry_price=signal.entry_price,
                quantity=0, position_value=0.0,
                stop_loss=signal.stop_loss, take_profit=signal.take_profit,
                rejection_reason="Insufficient capital for minimum position",
            )

        position_value = quantity * signal.entry_price
        risk_amount = quantity * abs(signal.entry_price - signal.stop_loss)

        # Check if we have enough cash
        if position_value > portfolio.cash:
            return PaperTradeResult(
                status="rejected", symbol=signal.symbol,
                direction=signal.direction, entry_price=signal.entry_price,
                quantity=0, position_value=0.0,
                stop_loss=signal.stop_loss, take_profit=signal.take_profit,
                rejection_reason="Insufficient cash",
            )

        # Calculate expected P&L
        if signal.direction == "long":
            expected_pnl = quantity * (signal.take_profit - signal.entry_price)
        else:
            expected_pnl = quantity * (signal.entry_price - signal.take_profit)

        # Update portfolio
        portfolio.cash -= position_value
        portfolio.positions[signal.symbol] = {
            "direction": signal.direction,
            "entry_price": signal.entry_price,
            "quantity": quantity,
            "position_value": position_value,
            "stop_loss": signal.stop_loss,
            "take_profit": signal.take_profit,
            "risk_amount": risk_amount,
            "entry_time": datetime.now().isoformat(),
        }
        portfolio.total_value = portfolio.cash + sum(
            p.get("position_value", 0) for p in portfolio.positions.values()
        )

        trade_record = {
            "symbol": signal.symbol,
            "direction": signal.direction,
            "entry": signal.entry_price,
            "quantity": quantity,
            "value": position_value,
            "status": "open",
            "timestamp": datetime.now().isoformat(),
        }
        portfolio.trade_history.append(trade_record)
        self._trade_history.append(trade_record)

        result = PaperTradeResult(
            status="executed", symbol=signal.symbol,
            direction=signal.direction, entry_price=signal.entry_price,
            quantity=quantity, position_value=position_value,
            stop_loss=signal.stop_loss, take_profit=signal.take_profit,
            expected_pnl=round(expected_pnl, 2),
            risk_amount=round(risk_amount, 2),
        )
        logger.info(f"[{self.name}] PAPER TRADE EXECUTED: {signal.symbol} x{quantity} "
                    f"value=${position_value:,.2f} risk=${risk_amount:,.2f}")
        return result

    def risk_analysis(self, portfolio: Portfolio) -> RiskReport:
        """
        Comprehensive portfolio risk analysis.

        Calculates Value at Risk (VaR), Expected Shortfall (CVaR),
        beta, correlation matrix, and stress test scenarios.

        Args:
            portfolio: Current portfolio state

        Returns:
            RiskReport: Complete risk assessment
        """
        logger.info(f"[{self.name}] Running comprehensive risk analysis...")

        positions = portfolio.positions
        if not positions:
            logger.warning("No positions - returning default risk report")
            return RiskReport(
                var_95=0.0, var_99=0.0, cvar=0.0, beta=1.0,
                correlation_matrix={}, stress_test_results={},
                portfolio_volatility=0.0, diversification_score=0.0,
            )

        # Generate historical returns for each position
        symbol_returns: Dict[str, List[float]] = {}
        for sym in positions:
            prices = _generate_mock_prices(100.0, 252, 0.018)
            symbol_returns[sym] = [(prices[i] / prices[i - 1]) - 1
                                    for i in range(1, len(prices))]

        # Portfolio returns (weighted)
        total_position_value = sum(p.get("position_value", 0) for p in positions.values())
        portfolio_returns = []
        for i in range(251):
            daily_ret = 0.0
            for sym, pos in positions.items():
                weight = pos.get("position_value", 0) / max(total_position_value, 1)
                if i < len(symbol_returns.get(sym, [])):
                    daily_ret += weight * symbol_returns[sym][i]
            portfolio_returns.append(daily_ret)

        # Value at Risk (historical simulation)
        if portfolio_returns:
            sorted_returns = sorted(portfolio_returns)
            var_95_idx = int(0.05 * len(sorted_returns))
            var_99_idx = int(0.01 * len(sorted_returns))
            var_95 = abs(sorted_returns[var_95_idx]) * portfolio.total_value
            var_99 = abs(sorted_returns[var_99_idx]) * portfolio.total_value
            # CVaR = average of returns beyond VaR
            cvar_returns = sorted_returns[:var_99_idx] if var_99_idx > 0 else [0]
            cvar = abs(_mean(cvar_returns)) * portfolio.total_value
        else:
            var_95, var_99, cvar = 0.0, 0.0, 0.0

        # Portfolio volatility
        port_vol = _std(portfolio_returns) * math.sqrt(252) if portfolio_returns else 0.0

        # Correlation matrix
        symbols = list(positions.keys())
        corr_matrix = {}
        for i, s1 in enumerate(symbols):
            corr_matrix[s1] = {}
            for s2 in symbols:
                if s1 == s2:
                    corr_matrix[s1][s2] = 1.0
                else:
                    r1 = symbol_returns.get(s1, [])
                    r2 = symbol_returns.get(s2, [])
                    min_len = min(len(r1), len(r2))
                    if min_len > 1:
                        corr_matrix[s1][s2] = round(_correlation(r1[:min_len], r2[:min_len]), 4)
                    else:
                        corr_matrix[s1][s2] = 0.0

        # Beta calculation (vs mock market)
        market_returns = [random.gauss(0.0003, 0.012) for _ in range(252)]
        min_len = min(len(portfolio_returns), len(market_returns))
        if min_len > 1 and _std(market_returns[:min_len]) > 0:
            cov = sum((portfolio_returns[i] - _mean(portfolio_returns[:min_len])) *
                      (market_returns[i] - _mean(market_returns[:min_len]))
                      for i in range(min_len)) / min_len
            market_var = _std(market_returns[:min_len]) ** 2
            beta = cov / market_var if market_var > 0 else 1.0
        else:
            beta = 1.0

        # Stress testing
        stress_results = {
            "market_crash_2008": round(portfolio.total_value * random.uniform(-0.35, -0.15), 2),
            "covid_crash": round(portfolio.total_value * random.uniform(-0.25, -0.10), 2),
            "interest_rate_shock": round(portfolio.total_value * random.uniform(-0.15, -0.05), 2),
            "inflation_spike": round(portfolio.total_value * random.uniform(-0.20, -0.08), 2),
            "geopolitical_crisis": round(portfolio.total_value * random.uniform(-0.30, -0.12), 2),
            "tech_bubble_burst": round(portfolio.total_value * random.uniform(-0.40, -0.20), 2),
        }

        # Diversification score (inverse of average correlation)
        off_diag_corrs = []
        for i, s1 in enumerate(symbols):
            for s2 in symbols[i + 1:]:
                off_diag_corrs.append(abs(corr_matrix[s1].get(s2, 0)))
        avg_corr = _mean(off_diag_corrs) if off_diag_corrs else 0
        div_score = max(0, 1 - avg_corr)

        # Tail risk score
        tail_risk = var_99 / max(portfolio.total_value, 1)

        report = RiskReport(
            var_95=round(var_95, 2),
            var_99=round(var_99, 2),
            cvar=round(cvar, 2),
            beta=round(beta, 4),
            correlation_matrix=corr_matrix,
            stress_test_results=stress_results,
            portfolio_volatility=round(port_vol, 4),
            diversification_score=round(div_score, 4),
            leverage_exposure=0.0,  # No leverage in paper trading
            tail_risk_score=round(tail_risk, 4),
        )

        logger.info(f"[{self.name}] Risk: VaR(95%)=${var_95:,.2f}, "
                    f"Beta={beta:.3f}, Vol={port_vol:.2%}")
        return report

    def optimize_portfolio(
        self,
        portfolio: Portfolio,
        target_return: float = 0.15,
    ) -> OptimizationResult:
        """
        Portfolio optimization using Modern Portfolio Theory (Markowitz).

        Calculates the efficient frontier and provides optimal weights
        for target return with minimum volatility.

        Args:
            portfolio: Current portfolio state
            target_return: Target annualized return (decimal)

        Returns:
            OptimizationResult: Optimal allocation and efficient frontier
        """
        logger.info(f"[{self.name}] Optimizing portfolio for {target_return:.1%} target return...")

        symbols = list(portfolio.positions.keys())
        if not symbols:
            logger.warning("Empty portfolio - cannot optimize")
            return OptimizationResult(
                target_return=target_return, optimal_weights={},
                expected_return=0.0, expected_volatility=0.0,
                sharpe_ratio=0.0, efficient_frontier=[],
                rebalancing_trades=[], sector_allocation={},
            )

        # Generate mock historical returns and statistics
        n_assets = len(symbols)
        returns_data = {}
        for sym in symbols:
            prices = _generate_mock_prices(100.0, 252, random.uniform(0.01, 0.03))
            returns_data[sym] = [(prices[i] / prices[i - 1]) - 1
                                  for i in range(1, len(prices))]

        expected_returns = {sym: _mean(rets) * 252 for sym, rets in returns_data.items()}
        volatilities = {sym: _std(rets) * math.sqrt(252) for sym, rets in returns_data.items()}

        # Correlation matrix
        correlations = {}
        for i, s1 in enumerate(symbols):
            for j, s2 in enumerate(symbols):
                if i == j:
                    correlations[(s1, s2)] = 1.0
                else:
                    min_len = min(len(returns_data[s1]), len(returns_data[s2]))
                    correlations[(s1, s2)] = _correlation(
                        returns_data[s1][:min_len], returns_data[s2][:min_len]
                    )

        # Monte Carlo simulation for efficient frontier
        n_portfolios = 5000
        frontier_points = []
        best_sharpe = -float('inf')
        best_weights = [1.0 / n_assets] * n_assets

        random.seed(42)
        for _ in range(n_portfolios):
            weights = [random.random() for _ in range(n_assets)]
            total = sum(weights)
            weights = [w / total for w in weights]

            port_ret = sum(w * expected_returns[sym] for w, sym in zip(weights, symbols))

            # Portfolio variance
            port_var = 0.0
            for i, s1 in enumerate(symbols):
                for j, s2 in enumerate(symbols):
                    port_var += (weights[i] * weights[j] *
                                 volatilities[s1] * volatilities[s2] *
                                 correlations[(s1, s2)])
            port_vol = math.sqrt(max(port_var, 0))

            frontier_points.append((port_ret, port_vol))

            rf_rate = 0.045  # Risk-free rate
            sharpe = (port_ret - rf_rate) / port_vol if port_vol > 0 else 0
            if sharpe > best_sharpe:
                best_sharpe = sharpe
                best_weights = weights[:]

        # Build efficient frontier (Pareto optimal points)
        frontier_points.sort(key=lambda x: x[1])
        efficient_frontier = []
        max_ret = -float('inf')
        for ret, vol in frontier_points:
            if ret > max_ret:
                max_ret = ret
                efficient_frontier.append((round(vol, 4), round(ret, 4)))

        optimal_weights = {sym: round(w, 4) for sym, w in zip(symbols, best_weights)}
        opt_return = sum(w * expected_returns[sym] for w, sym in zip(best_weights, symbols))

        # Portfolio variance for optimal
        opt_var = 0.0
        for i, s1 in enumerate(symbols):
            for j, s2 in enumerate(symbols):
                opt_var += (best_weights[i] * best_weights[j] *
                            volatilities[s1] * volatilities[s2] *
                            correlations[(s1, s2)])
        opt_vol = math.sqrt(max(opt_var, 0))

        # Rebalancing recommendations
        current_values = {sym: portfolio.positions[sym].get("position_value", 0)
                          for sym in symbols}
        total_value = sum(current_values.values()) + portfolio.cash
        rebalancing = []
        for sym in symbols:
            target_value = total_value * optimal_weights.get(sym, 0)
            current = current_values.get(sym, 0)
            diff = target_value - current
            if abs(diff) > total_value * 0.01:  # 1% threshold
                rebalancing.append({
                    "symbol": sym,
                    "action": "buy" if diff > 0 else "sell",
                    "amount": round(abs(diff), 2),
                    "current_weight": round(current / max(total_value, 1), 4),
                    "target_weight": optimal_weights.get(sym, 0),
                })

        # Sector allocation (mock)
        sectors = ["Technology", "Healthcare", "Finance", "Energy",
                   "Consumer", "Industrial"]
        sector_alloc = {}
        for sym in symbols:
            sector = random.choice(sectors)
            sector_alloc[sector] = sector_alloc.get(sector, 0) + optimal_weights.get(sym, 0)

        result = OptimizationResult(
            target_return=round(target_return, 4),
            optimal_weights=optimal_weights,
            expected_return=round(opt_return, 4),
            expected_volatility=round(opt_vol, 4),
            sharpe_ratio=round(best_sharpe, 4),
            efficient_frontier=efficient_frontier[:50],
            rebalancing_trades=rebalancing,
            sector_allocation={k: round(v, 4) for k, v in sector_alloc.items()},
        )

        logger.info(f"[{self.name}] Optimization: ExpRet={opt_return:.2%}, "
                    f"ExpVol={opt_vol:.2%}, Sharpe={best_sharpe:.3f}")
        return result

    # ========================================================================
    # SECTION 3: ADVANCED ANALYTICS
    # ========================================================================

    def detect_market_regime(self) -> str:
        """
        Detect current market regime classification.

        Analyzes price action, volatility, and volume patterns to
        classify the market as bull/bear/sideways and assess
        volatility and liquidity regimes.

        Returns:
            String describing the detected market regime
        """
        logger.info(f"[{self.name}] Detecting market regime...")

        # Generate mock market data for regime detection
        prices = _generate_mock_prices(4500.0, 90, 0.012)
        volumes = [random.randint(2000000000, 5000000000) for _ in range(90)]

        # Trend detection
        sma_20 = _mean(prices[-20:]) if len(prices) >= 20 else _mean(prices)
        sma_50 = _mean(prices[-50:]) if len(prices) >= 50 else _mean(prices)
        current = prices[-1]

        if current > sma_20 > sma_50 * 1.02:
            trend_regime = "bull_market"
        elif current < sma_20 < sma_50 * 0.98:
            trend_regime = "bear_market"
        else:
            trend_regime = "sideways_market"

        # Volatility regime
        returns = [(prices[i] / prices[i - 1]) - 1 for i in range(1, len(prices))]
        vol = _std(returns[-20:]) * math.sqrt(252) if len(returns) >= 20 else 0.15

        if vol > 0.25:
            vol_regime = "high_volatility"
        elif vol > 0.15:
            vol_regime = "normal_volatility"
        else:
            vol_regime = "low_volatility"

        # Liquidity regime
        avg_volume = _mean(volumes[-20:]) if len(volumes) >= 20 else _mean(volumes)
        if avg_volume > 3500000000:
            liq_regime = "high_liquidity"
        elif avg_volume > 2500000000:
            liq_regime = "normal_liquidity"
        else:
            liq_regime = "low_liquidity"

        regime = f"{trend_regime}_{vol_regime}_{liq_regime}"
        self._data_cache["regime"] = regime

        logger.info(f"[{self.name}] Regime: {regime}")
        return regime

    def predict_volatility(
        self,
        symbol: str,
        horizon: int = 30,
    ) -> VolatilityForecast:
        """
        Predict future volatility using GARCH-inspired modeling.

        Models volatility clustering and mean reversion to forecast
        future volatility over the specified horizon.

        Args:
            symbol: Ticker symbol to forecast
            horizon: Forecast horizon in trading days

        Returns:
            VolatilityForecast: Predicted volatility and confidence intervals
        """
        logger.info(f"[{self.name}] Forecasting volatility for {symbol} ({horizon}d horizon)...")

        # Generate historical returns
        prices = _generate_mock_prices(100.0, 252, 0.02)
        returns = [(prices[i] / prices[i - 1]) - 1 for i in range(1, len(prices))]

        # Calculate current volatility
        current_vol = _std(returns[-20:]) * math.sqrt(252) if len(returns) >= 20 else 0.20

        # GARCH-inspired forecast (simplified)
        # vol_t+1 = omega + alpha * r_t^2 + beta * vol_t
        omega = 0.000001
        alpha = 0.10
        beta = 0.85
        long_run_var = omega / (1 - alpha - beta) if (alpha + beta) < 1 else 0.0001

        forecasted_vols = []
        vol_pred = current_vol / math.sqrt(252)  # Daily vol
        for _ in range(horizon):
            last_return_sq = returns[-1] ** 2 if returns else 0.0001
            vol_pred = math.sqrt(omega + alpha * last_return_sq + beta * vol_pred ** 2)
            forecasted_vols.append(vol_pred * math.sqrt(252))

        forecasted_vol = _mean(forecasted_vols) if forecasted_vols else current_vol

        # Volatility trend
        if forecasted_vol > current_vol * 1.1:
            trend = "increasing"
        elif forecasted_vol < current_vol * 0.9:
            trend = "decreasing"
        else:
            trend = "stable"

        # Volatility cone (percentiles of historical vol)
        rolling_vols = []
        for i in range(20, len(returns)):
            window = returns[i - 20:i]
            rolling_vols.append(_std(window) * math.sqrt(252))

        cone = [
            _percentile(rolling_vols, 0.10) if rolling_vols else current_vol * 0.7,
            _percentile(rolling_vols, 0.25) if rolling_vols else current_vol * 0.85,
            _percentile(rolling_vols, 0.50) if rolling_vols else current_vol,
            _percentile(rolling_vols, 0.75) if rolling_vols else current_vol * 1.15,
            _percentile(rolling_vols, 0.90) if rolling_vols else current_vol * 1.3,
        ]

        ci = {
            "lower_90": round(current_vol * 0.7, 4),
            "upper_90": round(current_vol * 1.3, 4),
            "lower_95": round(current_vol * 0.6, 4),
            "upper_95": round(current_vol * 1.4, 4),
        }

        forecast = VolatilityForecast(
            symbol=symbol,
            forecast_horizon=horizon,
            current_volatility=round(current_vol, 4),
            forecasted_volatility=round(forecasted_vol, 4),
            volatility_trend=trend,
            volatility_cone=[round(v, 4) for v in cone],
            confidence_intervals=ci,
        )

        logger.info(f"[{self.name}] Vol forecast: current={current_vol:.2%}, "
                    f"forecast={forecasted_vol:.2%}, trend={trend}")
        return forecast

    def generate_report(self, portfolio: Optional[Portfolio] = None) -> FinancialReport:
        """
        Generate comprehensive financial analysis report.

        Creates a detailed report including portfolio summary, risk metrics,
        open positions, market outlook, and strategy recommendations.

        Args:
            portfolio: Optional portfolio to include in report

        Returns:
            FinancialReport: Complete financial analysis
        """
        logger.info(f"[{self.name}] Generating comprehensive financial report...")

        now = datetime.now().isoformat()

        # Portfolio summary
        if portfolio is None:
            portfolio = Portfolio(
                cash=100000.0, positions={},
                total_value=100000.0, daily_pnl=0.0, total_pnl=0.0,
            )

        port_summary = {
            "total_value": round(portfolio.total_value, 2),
            "cash": round(portfolio.cash, 2),
            "open_positions": len(portfolio.positions),
            "daily_pnl": round(portfolio.daily_pnl, 2),
            "total_pnl": round(portfolio.total_pnl, 2),
            "margin_used": round(portfolio.margin_used, 2),
            "margin_available": round(portfolio.margin_available, 2),
        }

        # Risk metrics
        if portfolio.positions:
            risk = self.risk_analysis(portfolio)
            risk_metrics = {
                "var_95": risk.var_95,
                "var_99": risk.var_99,
                "cvar": risk.cvar,
                "beta": risk.beta,
                "portfolio_volatility": risk.portfolio_volatility,
                "diversification_score": risk.diversification_score,
                "tail_risk_score": risk.tail_risk_score,
            }
        else:
            risk_metrics = {
                "var_95": 0, "var_99": 0, "cvar": 0,
                "beta": 1.0, "portfolio_volatility": 0,
                "diversification_score": 0, "tail_risk_score": 0,
            }

        # Open positions detail
        open_positions = []
        for sym, pos in portfolio.positions.items():
            open_positions.append({
                "symbol": sym,
                "direction": pos.get("direction", "unknown"),
                "entry_price": pos.get("entry_price", 0),
                "quantity": pos.get("quantity", 0),
                "position_value": pos.get("position_value", 0),
                "stop_loss": pos.get("stop_loss", 0),
                "take_profit": pos.get("take_profit", 0),
            })

        # Recent trades
        recent_trades = portfolio.trade_history[-10:] if portfolio.trade_history else []

        # Market outlook
        macro = self.ingest_macro_data()
        sentiment = self.ingest_news_sentiment()
        regime = self.detect_market_regime()

        outlook_parts = []
        if "bull" in regime:
            outlook_parts.append("Bullish trend detected")
        elif "bear" in regime:
            outlook_parts.append("Bearish trend detected - caution advised")
        else:
            outlook_parts.append("Sideways market - range-bound strategies favored")

        if "high_volatility" in regime:
            outlook_parts.append("High volatility regime - reduce position sizes")
        outlook_parts.append(f"Fed rate at {macro.fed_rate:.2f}%")
        outlook_parts.append(f"News sentiment: {sentiment.trend}")

        market_outlook = "; ".join(outlook_parts)

        # Strategy performance summary
        strategy_perf = {}
        for strat in ["combined", "trend", "mean_reversion", "momentum"]:
            bt = self.backtest_strategy(strat, "SPY", "2022-01-01", "2024-01-01")
            strategy_perf[strat] = {
                "total_return": bt.total_return,
                "sharpe_ratio": bt.sharpe_ratio,
                "max_drawdown": bt.max_drawdown,
                "win_rate": bt.win_rate,
            }

        # Recommendations
        recommendations = []
        if risk_metrics.get("var_95", 0) > portfolio.total_value * 0.05:
            recommendations.append("Reduce position sizes - VaR exceeds 5% threshold")
        if risk_metrics.get("diversification_score", 0) < 0.3:
            recommendations.append("Increase diversification - correlation too high")
        if "high_volatility" in regime:
            recommendations.append("Consider volatility-adjusted position sizing")
        if macro.vix > 25:
            recommendations.append("Elevated VIX - defensive positioning recommended")
        if not recommendations:
            recommendations.append("Portfolio within normal risk parameters")

        report = FinancialReport(
            generated_at=now,
            portfolio_summary=port_summary,
            risk_metrics=risk_metrics,
            open_positions=open_positions,
            recent_trades=recent_trades,
            market_outlook=market_outlook,
            strategy_performance=strategy_perf,
            recommendations=recommendations,
        )

        logger.info(f"[{self.name}] Report generated at {now}")
        return report

    # ========================================================================
    # UTILITY METHODS
    # ========================================================================

    def get_status(self) -> dict:
        """Return engine status and health metrics."""
        return {
            "engine": self.name,
            "version": self.version,
            "session_id": self._session_id,
            "api_connected": self.api_connected,
            "numpy_available": _HAS_NUMPY,
            "pandas_available": _HAS_PANDAS,
            "risk_limits": self.risk_limits,
            "cache_size": len(self._data_cache),
            "trade_count": len(self._trade_history),
            "timestamp": datetime.now().isoformat(),
        }

    def reset(self) -> None:
        """Reset engine state - clears cache and trade history."""
        self._data_cache.clear()
        self._trade_history.clear()
        logger.info(f"[{self.name}] Engine state reset")

    def close_position(self, symbol: str, portfolio: Portfolio,
                       exit_price: Optional[float] = None) -> dict:
        """
        Close an open position (paper trade).

        Args:
            symbol: Symbol to close
            portfolio: Portfolio containing the position
            exit_price: Optional override exit price

        Returns:
            dict with closing details
        """
        if symbol not in portfolio.positions:
            return {"status": "error", "reason": f"No position in {symbol}"}

        pos = portfolio.positions[symbol]
        close_price = exit_price or pos["entry_price"] * (1 + random.uniform(-0.05, 0.08))

        if pos["direction"] == "long":
            pnl = (close_price - pos["entry_price"]) * pos["quantity"]
        else:
            pnl = (pos["entry_price"] - close_price) * pos["quantity"]

        portfolio.cash += pos["position_value"] + pnl
        portfolio.total_pnl += pnl
        portfolio.daily_pnl += pnl

        result = {
            "symbol": symbol,
            "direction": pos["direction"],
            "entry": pos["entry_price"],
            "exit": round(close_price, 2),
            "quantity": pos["quantity"],
            "pnl": round(pnl, 2),
            "status": "closed",
            "timestamp": datetime.now().isoformat(),
        }
        portfolio.trade_history.append(result)
        del portfolio.positions[symbol]
        portfolio.total_value = portfolio.cash + sum(
            p.get("position_value", 0) for p in portfolio.positions.values()
        )

        logger.info(f"[{self.name}] Position closed: {symbol} P&L=${pnl:,.2f}")
        return result


# ============================================================================
# SELF-TEST BLOCK
# ============================================================================

if __name__ == "__main__":
    print("=" * 72)
    print("  OMNISCIENT FINANCIAL DOMINANCE ENGINE - SELF TEST")
    print("  FOR EDUCATIONAL PURPOSES ONLY - PAPER TRADING ONLY")
    print("=" * 72)

    # Initialize engine
    engine = FinancialDominanceEngine(name="TEST-ENGINE")
    status = engine.get_status()
    assert status["engine"] == "TEST-ENGINE"
    assert status["version"] == FinancialDominanceEngine.VERSION
    print(f"\n[PASS] Engine initialized: {status['engine']} v{status['version']}")

    # Test 1: Macro data ingestion
    macro = engine.ingest_macro_data()
    assert isinstance(macro, MacroData)
    assert 0 <= macro.fed_rate <= 20
    assert macro.vix >= 0
    assert macro.sentiment in ["bullish", "neutral", "bearish", "cautious"]
    print(f"[PASS] Macro data: Fed={macro.fed_rate:.2f}%, VIX={macro.vix:.1f}")

    # Test 2: Order book analysis
    symbols = ["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA"]
    order_books = engine.ingest_order_books(symbols)
    assert len(order_books) == len(symbols)
    for sym, ob in order_books.items():
        assert ob.symbol == sym
        assert ob.best_bid < ob.best_ask
        assert ob.spread > 0
        assert 0 <= ob.liquidity_score <= 1
    print(f"[PASS] Order books: {len(order_books)} symbols analyzed")

    # Test 3: News sentiment
    sentiment = engine.ingest_news_sentiment("technology stocks")
    assert isinstance(sentiment, SentimentAnalysis)
    assert -1 <= sentiment.overall_score <= 1
    assert len(sentiment.trending_topics) > 0
    print(f"[PASS] Sentiment: {sentiment.trend} (score={sentiment.overall_score:.3f})")

    # Test 4: Signal generation
    signals = engine.generate_signals("AAPL", strategy="combined")
    assert len(signals) > 0
    for sig in signals:
        assert sig.symbol == "AAPL"
        assert sig.direction in ["long", "short", "neutral"]
        assert 0 <= sig.confidence <= 1
        assert sig.stop_loss > 0
        assert sig.take_profit > 0
    print(f"[PASS] Signals: {len(signals)} signals generated for AAPL")

    # Test 5: Backtesting
    bt = engine.backtest_strategy("combined", "SPY", "2022-01-01", "2024-01-01")
    assert isinstance(bt, BacktestResult)
    assert bt.total_trades > 0
    assert -1 <= bt.total_return <= 5  # Reasonable bounds
    assert 0 <= bt.win_rate <= 1
    assert bt.max_drawdown >= 0
    assert len(bt.equity_curve) > 0
    assert len(bt.trade_log) == bt.total_trades
    print(f"[PASS] Backtest: Return={bt.total_return:.2%}, "
          f"Sharpe={bt.sharpe_ratio:.2f}, Trades={bt.total_trades}")

    # Test 6: Paper trading
    test_portfolio = Portfolio(
        cash=100000.0,
        positions={},
        total_value=100000.0,
        daily_pnl=0.0,
        total_pnl=0.0,
    )
    if signals and signals[0].direction in ["long", "short"]:
        trade_result = engine.paper_trade(signals[0], test_portfolio)
        assert trade_result.status == "executed"
        assert trade_result.quantity > 0
        assert trade_result.position_value > 0
        assert trade_result.symbol == signals[0].symbol
        print(f"[PASS] Paper trade: {trade_result.symbol} x{trade_result.quantity} "
              f"@ ${trade_result.position_value:,.2f}")
    else:
        print("[SKIP] Paper trade - no actionable signal")

    # Test 7: Risk analysis
    risk_report = engine.risk_analysis(test_portfolio)
    assert isinstance(risk_report, RiskReport)
    assert risk_report.var_95 >= 0
    assert risk_report.var_99 >= risk_report.var_95
    assert len(risk_report.stress_test_results) > 0
    print(f"[PASS] Risk: VaR(95%)=${risk_report.var_95:,.2f}, "
          f"Beta={risk_report.beta:.3f}")

    # Test 8: Portfolio optimization
    # First add more positions
    for sym in ["MSFT", "GOOGL"]:
        sigs = engine.generate_signals(sym)
        if sigs and sigs[0].direction in ["long", "short"]:
            engine.paper_trade(sigs[0], test_portfolio)

    opt = engine.optimize_portfolio(test_portfolio, target_return=0.15)
    assert isinstance(opt, OptimizationResult)
    assert len(opt.optimal_weights) > 0
    assert all(0 <= w <= 1 for w in opt.optimal_weights.values())
    assert len(opt.efficient_frontier) > 0
    print(f"[PASS] Optimization: ExpRet={opt.expected_return:.2%}, "
          f"Sharpe={opt.sharpe_ratio:.3f}")

    # Test 9: Market regime detection
    regime = engine.detect_market_regime()
    assert isinstance(regime, str)
    assert len(regime.split("_")) >= 3
    assert any(r in regime for r in ["bull", "bear", "sideways"])
    assert any(r in regime for r in ["volatility", "liquidity"])
    print(f"[PASS] Regime: {regime}")

    # Test 10: Volatility forecasting
    vol_forecast = engine.predict_volatility("AAPL", horizon=30)
    assert isinstance(vol_forecast, VolatilityForecast)
    assert vol_forecast.symbol == "AAPL"
    assert vol_forecast.forecast_horizon == 30
    assert vol_forecast.current_volatility > 0
    assert vol_forecast.volatility_trend in ["increasing", "decreasing", "stable"]
    assert len(vol_forecast.volatility_cone) == 5
    print(f"[PASS] Vol forecast: current={vol_forecast.current_volatility:.2%}, "
          f"predicted={vol_forecast.forecasted_volatility:.2%}")

    # Test 11: Financial report generation
    report = engine.generate_report(test_portfolio)
    assert isinstance(report, FinancialReport)
    assert report.generated_at is not None
    assert "total_value" in report.portfolio_summary
    assert len(report.recommendations) > 0
    print(f"[PASS] Report generated: {len(report.recommendations)} recommendations")

    # Test 12: Position closing
    if test_portfolio.positions:
        first_sym = list(test_portfolio.positions.keys())[0]
        close_result = engine.close_position(first_sym, test_portfolio)
        assert close_result["status"] == "closed"
        assert "pnl" in close_result
        print(f"[PASS] Position closed: {first_sym} P&L=${close_result['pnl']:,.2f}")

    # Test 13: Engine reset
    engine.reset()
    assert len(engine._data_cache) == 0
    print("[PASS] Engine reset successful")

    # Test 14: Kelly criterion utility
    kelly = _kelly_criterion(win_rate=0.55, avg_win=150, avg_loss=100)
    assert 0 <= kelly <= 0.25
    print(f"[PASS] Kelly criterion: {kelly:.2%} optimal position size")

    # Test 15: Pure Python indicator verification
    test_prices = [100, 102, 101, 105, 103, 107, 106, 108, 110, 112]
    rsi_val = _rsi(test_prices, period=5)
    assert 0 <= rsi_val <= 100
    bb_u, bb_m, bb_l = _bollinger_bands(test_prices, period=5)
    assert bb_u > bb_m > bb_l
    print(f"[PASS] Technical indicators: RSI={rsi_val:.1f}, BB=({bb_l:.1f}, {bb_m:.1f}, {bb_u:.1f})")

    print("\n" + "=" * 72)
    print("  ALL 15 TESTS PASSED - ENGINE OPERATIONAL")
    print("  REMEMBER: FOR EDUCATIONAL PURPOSES ONLY")
    print("  PAPER TRADING ONLY - NO REAL MONEY AT RISK")
    print("=" * 72)
