#!/usr/bin/env python3
"""
================================================================================
                    JARVIS BRAINIAC - TRADING ENGINE
================================================================================
Provides TRADING CAPABILITIES and KNOWLEDGE — not autonomous trading.
ALL trades require explicit user approval and deposited funds.

This module implements a comprehensive trading engine that covers:
    - Market Analysis (stocks, crypto, forex)
    - Strategy Development & Backtesting
    - Risk Management (position sizing, VaR, portfolio analytics)
    - Trade Execution (with mandatory approval gates)
    - Mock / Paper Trading for safe testing

Author      : JARVIS BRAINIAC Runtime
Version     : 1.0.0
Safety Level: HIGH — No autonomous execution without explicit user consent.
================================================================================
"""

from __future__ import annotations

import hashlib
import json
import sys as _sys

# Guard against local modules shadowing stdlib (e.g. logging.py in same pkg)
_orig_path = list(_sys.path)
_sys.path = [p for p in _sys.path if p != "" and not p.endswith("agency")]
import logging
_sys.path[:] = _orig_path
del _sys, _orig_path

import random
import time
import uuid
import warnings
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple, Union

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Module-level logger
# ---------------------------------------------------------------------------
logger = logging.getLogger("jarvis.trading_engine")

# ---------------------------------------------------------------------------
# Enums & Constants
# ---------------------------------------------------------------------------

class AssetClass(Enum):
    """Supported asset classes."""
    EQUITY = "equity"
    CRYPTO = "crypto"
    FOREX = "forex"
    COMMODITY = "commodity"


class OrderType(Enum):
    """Supported order types."""
    MARKET = "market"
    LIMIT = "limit"
    STOP = "stop"
    STOP_LIMIT = "stop_limit"
    TRAILING_STOP = "trailing_stop"


class OrderSide(Enum):
    """Trade direction."""
    BUY = "buy"
    SELL = "sell"


class OrderStatus(Enum):
    """Lifecycle states for a trade."""
    PENDING_APPROVAL = "pending_approval"
    APPROVED = "approved"
    REJECTED = "rejected"
    SUBMITTED = "submitted"
    PARTIAL_FILL = "partial_fill"
    FILLED = "filled"
    CANCELLED = "cancelled"
    EXPIRED = "expired"
    ERROR = "error"


class Signal(Enum):
    """Trading signals generated by strategies."""
    STRONG_BUY = 2
    BUY = 1
    HOLD = 0
    SELL = -1
    STRONG_SELL = -2


# Technical indicator defaults
INDICATOR_PERIODS = {
    "sma_short": 20,
    "sma_long": 50,
    "ema_fast": 12,
    "ema_slow": 26,
    "rsi": 14,
    "macd_fast": 12,
    "macd_slow": 26,
    "macd_signal": 9,
    "bollinger": 20,
    "atr": 14,
}

APPROVAL_PROMPT_TEMPLATE = """
╔══════════════════════════════════════════════════════════════════════════════╗
║                     TRADE APPROVAL REQUIRED                                  ║
╠══════════════════════════════════════════════════════════════════════════════╣
  Action      : {side} {quantity} x {symbol}
  Order Type  : {order_type}
  Price       : {price}
  Est. Value  : ${estimated_value:,.2f}
  Strategy    : {strategy}
  Reason      : {reason}
╠══════════════════════════════════════════════════════════════════════════════╣
  ⚠️  This action requires YOUR explicit approval. No funds will be moved     ║
     without your consent. Reply APPROVE to proceed or REJECT to cancel.       ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------

class TradingError(Exception):
    """Base exception for trading engine errors."""
    pass

class InsufficientFundsError(TradingError):
    """Raised when the user lacks deposited funds."""
    pass

class ApprovalRequiredError(TradingError):
    """Raised when a trade lacks explicit user approval."""
    pass

class InvalidOrderError(TradingError):
    """Raised when order parameters are invalid."""
    pass

class StrategyError(TradingError):
    """Raised when a strategy operation fails."""
    pass


# ---------------------------------------------------------------------------
# Utility / helper functions
# ---------------------------------------------------------------------------

def _generate_id(prefix: str = "TX") -> str:
    """Generate a unique trade / operation identifier."""
    return f"{prefix}-{uuid.uuid4().hex[:12].upper()}"


def _current_timestamp() -> str:
    """ISO-8601 timestamp."""
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _safe_json(obj: Any) -> Any:
    """Recursively convert NumPy / Pandas types to Python-native JSON."""
    if isinstance(obj, (np.integer, np.int64, np.int32)):
        return int(obj)
    if isinstance(obj, (np.floating, np.float64, np.float32)):
        return float(obj)
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, pd.Series):
        return obj.to_dict()
    if isinstance(obj, pd.DataFrame):
        return obj.to_dict(orient="records")
    if isinstance(obj, dict):
        return {k: _safe_json(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_safe_json(v) for v in obj]
    if isinstance(obj, Enum):
        return obj.value
    return obj


def _compute_sma(series: pd.Series, window: int) -> pd.Series:
    """Simple Moving Average."""
    return series.rolling(window=window, min_periods=1).mean()


def _compute_ema(series: pd.Series, span: int) -> pd.Series:
    """Exponential Moving Average."""
    return series.ewm(span=span, adjust=False, min_periods=1).mean()


def _compute_rsi(series: pd.Series, period: int = 14) -> pd.Series:
    """Relative Strength Index (0-100)."""
    delta = series.diff()
    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)
    avg_gain = gain.rolling(window=period, min_periods=1).mean()
    avg_loss = loss.rolling(window=period, min_periods=1).mean()
    rs = avg_gain / (avg_loss + 1e-12)
    return 100 - (100 / (1 + rs))


def _compute_macd(
    series: pd.Series, fast: int = 12, slow: int = 26, signal: int = 9
) -> Tuple[pd.Series, pd.Series, pd.Series]:
    """MACD line, Signal line, and Histogram."""
    ema_fast = _compute_ema(series, fast)
    ema_slow = _compute_ema(series, slow)
    macd_line = ema_fast - ema_slow
    signal_line = _compute_ema(macd_line, signal)
    histogram = macd_line - signal_line
    return macd_line, signal_line, histogram


def _compute_bollinger(
    series: pd.Series, window: int = 20, num_std: float = 2.0
) -> Tuple[pd.Series, pd.Series, pd.Series]:
    """Bollinger Bands — middle, upper, lower."""
    middle = _compute_sma(series, window)
    std = series.rolling(window=window, min_periods=1).std()
    upper = middle + num_std * std
    lower = middle - num_std * std
    return middle, upper, lower


def _compute_atr(high: pd.Series, low: pd.Series, close: pd.Series, period: int = 14) -> pd.Series:
    """Average True Range."""
    tr1 = high - low
    tr2 = (high - close.shift(1)).abs()
    tr3 = (low - close.shift(1)).abs()
    tr = pd.concat([tr1, tr2, tr3], axis=1).max(axis=1)
    return tr.rolling(window=period, min_periods=1).mean()


def _compute_sharpe(returns: pd.Series, risk_free: float = 0.02, periods: int = 252) -> float:
    """Annualised Sharpe ratio."""
    if returns.std() == 0:
        return 0.0
    return (returns.mean() - risk_free / periods) / (returns.std() + 1e-12) * np.sqrt(periods)


def _compute_max_drawdown(equity_curve: pd.Series) -> float:
    """Maximum drawdown as a negative fraction."""
    peak = equity_curve.cummax()
    drawdown = (equity_curve - peak) / (peak + 1e-12)
    return drawdown.min()


def _signal_from_score(score: float) -> Signal:
    """Map a numeric score to a Signal enum."""
    if score >= 1.5:
        return Signal.STRONG_BUY
    if score >= 0.5:
        return Signal.BUY
    if score <= -1.5:
        return Signal.STRONG_SELL
    if score <= -0.5:
        return Signal.SELL
    return Signal.HOLD


# =============================================================================
#  TRADING ENGINE
# =============================================================================

class TradingEngine:
    """
    Core trading engine for JARVIS BRAINIAC.

    Provides **analysis capabilities** and **trade execution interfaces**.
    No trade is executed without explicit user approval.

    Attributes:
        name          : Human-readable engine identifier.
        mode          : 'live' or 'paper'.
        max_position_pct : Max % of capital in a single position (default 20%).
        daily_loss_limit : Max % of capital that can be lost in one day.
    """

    def __init__(
        self,
        name: str = "JARVIS-TradingEngine",
        mode: str = "paper",
        max_position_pct: float = 0.20,
        daily_loss_limit: float = 0.05,
        risk_free_rate: float = 0.02,
    ):
        self.name = name
        self.mode = mode.lower().strip()
        self.max_position_pct = max_position_pct
        self.daily_loss_limit = daily_loss_limit
        self.risk_free_rate = risk_free_rate

        # In-memory storage (trade journal)
        self._trade_history: List[Dict[str, Any]] = []
        self._active_trades: Dict[str, Dict[str, Any]] = {}
        self._strategies: Dict[str, Dict[str, Any]] = {}
        self._user_approvals: Dict[str, bool] = {}

        logger.info("TradingEngine '%s' initialised in '%s' mode.", name, self.mode)

    # ------------------------------------------------------------------
    #  Internal helpers
    # ------------------------------------------------------------------

    def _record_trade(self, trade: Dict[str, Any]) -> None:
        """Persist a trade to the in-memory journal."""
        trade["recorded_at"] = _current_timestamp()
        self._trade_history.append(trade)
        if trade.get("trade_id"):
            self._active_trades[trade["trade_id"]] = trade
        logger.debug("Recorded trade %s", trade.get("trade_id", "N/A"))

    def _request_approval(self, order: Dict[str, Any]) -> bool:
        """
        Render an approval prompt and wait for explicit user consent.
        In an interactive environment this would block; here we log and
        stash the pending approval state for the caller to resolve.
        """
        trade_id = order.get("trade_id", _generate_id("TX"))
        quantity = order.get("quantity", 0)
        price = order.get("price", order.get("limit_price", 0.0))
        estimated_value = quantity * price

        prompt = APPROVAL_PROMPT_TEMPLATE.format(
            side=order.get("side", "BUY").upper(),
            quantity=quantity,
            symbol=order.get("symbol", "???"),
            order_type=order.get("order_type", "MARKET"),
            price=f"{price:,.4f}" if price else "MARKET",
            estimated_value=estimated_value,
            strategy=order.get("strategy", "manual"),
            reason=order.get("reason", "User-initiated trade."),
        )
        logger.info("Approval requested for trade %s", trade_id)
        # Store as pending — caller / external loop must confirm
        self._user_approvals[trade_id] = False
        order["approval_prompt"] = prompt
        order["trade_id"] = trade_id
        order["status"] = OrderStatus.PENDING_APPROVAL.value
        return False  # Not yet approved

    def _generate_price_history(
        self,
        symbol: str,
        periods: int = 252,
        start_price: float = 100.0,
        volatility: float = 0.02,
        drift: float = 0.0003,
        seed: Optional[int] = None,
    ) -> pd.DataFrame:
        """
        Generate synthetic OHLCV price history using geometric Brownian motion.
        Used for demonstration / testing when no external feed is available.
        """
        if seed is not None:
            np.random.seed(seed)
        dates = pd.date_range(end=datetime.now(timezone.utc), periods=periods, freq="B")
        returns = np.random.normal(drift, volatility, periods)
        prices = start_price * np.exp(np.cumsum(returns))
        # Build OHLCV around the close
        noise = volatility * prices * 0.3
        df = pd.DataFrame(
            {
                "date": dates,
                "open": prices + np.random.normal(0, noise * 0.5, periods),
                "high": prices + np.abs(np.random.normal(noise, noise * 0.3, periods)),
                "low": prices - np.abs(np.random.normal(noise, noise * 0.3, periods)),
                "close": prices,
                "volume": np.random.randint(1_000_000, 50_000_000, periods),
            }
        )
        df.set_index("date", inplace=True)
        return df

    # =================================================================
    #  MARKET ANALYSIS
    # =================================================================

    def analyze_stock(self, symbol: str) -> Dict[str, Any]:
        """
        Perform fundamental + technical analysis on a stock symbol.

        Returns a dict with:
            - symbol, asset_class
            - price_summary (current, change, change_pct)
            - technical_indicators (SMA, EMA, RSI, MACD, Bollinger, ATR)
            - signal (STRONG_BUY / BUY / HOLD / SELL / STRONG_SELL)
            - score (-2.0 to +2.0 composite)
            - analysis_notes (human-readable commentary)
        """
        logger.info("Analyzing stock: %s", symbol)
        data = self.get_price_history(symbol, period="6mo")
        if data.empty:
            raise TradingError(f"No price data available for {symbol}.")

        close = data["close"]
        high = data["high"]
        low = data["low"]
        volume = data.get("volume", pd.Series(index=close.index, data=0))

        # ---- Technical indicators ----
        sma20 = _compute_sma(close, INDICATOR_PERIODS["sma_short"])
        sma50 = _compute_sma(close, INDICATOR_PERIODS["sma_long"])
        ema12 = _compute_ema(close, INDICATOR_PERIODS["ema_fast"])
        ema26 = _compute_ema(close, INDICATOR_PERIODS["ema_slow"])
        rsi = _compute_rsi(close, INDICATOR_PERIODS["rsi"])
        macd_line, macd_signal, macd_hist = _compute_macd(close)
        bb_mid, bb_upper, bb_lower = _compute_bollinger(close)
        atr = _compute_atr(high, low, close)

        current_price = float(close.iloc[-1])
        prev_price = float(close.iloc[-2]) if len(close) > 1 else current_price
        change = current_price - prev_price
        change_pct = (change / (prev_price + 1e-12)) * 100

        # ---- Composite scoring (-2 to +2) ----
        score = 0.0
        notes: List[str] = []

        # Trend — SMA crossover
        if sma20.iloc[-1] > sma50.iloc[-1]:
            score += 0.5
            notes.append("Short-term SMA above long-term SMA (bullish trend).")
        else:
            score -= 0.5
            notes.append("Short-term SMA below long-term SMA (bearish trend).")

        # RSI
        current_rsi = float(rsi.iloc[-1])
        if current_rsi < 30:
            score += 0.6
            notes.append(f"RSI oversold ({current_rsi:.1f}) — potential reversal up.")
        elif current_rsi > 70:
            score -= 0.6
            notes.append(f"RSI overbought ({current_rsi:.1f}) — potential reversal down.")
        else:
            notes.append(f"RSI neutral ({current_rsi:.1f}).")

        # MACD
        if macd_hist.iloc[-1] > 0 and macd_hist.iloc[-2] <= 0:
            score += 0.5
            notes.append("MACD histogram turned positive (bullish crossover).")
        elif macd_hist.iloc[-1] < 0 and macd_hist.iloc[-2] >= 0:
            score -= 0.5
            notes.append("MACD histogram turned negative (bearish crossover).")
        else:
            notes.append("MACD histogram continuing current trend.")

        # Bollinger position
        if current_price <= bb_lower.iloc[-1]:
            score += 0.4
            notes.append("Price at lower Bollinger Band — potential bounce.")
        elif current_price >= bb_upper.iloc[-1]:
            score -= 0.4
            notes.append("Price at upper Bollinger Band — potential pullback.")
        else:
            notes.append("Price within Bollinger Bands — normal range.")

        # Volume confirmation
        avg_vol = volume.rolling(20, min_periods=1).mean().iloc[-1]
        if volume.iloc[-1] > avg_vol * 1.5:
            notes.append("Volume spike detected — confirming move strength.")
            score += np.sign(score) * 0.2 if score != 0 else 0.0

        # Clamp score and derive signal
        score = max(-2.0, min(2.0, score))
        signal = _signal_from_score(score)

        result = {
            "symbol": symbol.upper(),
            "asset_class": AssetClass.EQUITY.value,
            "timestamp": _current_timestamp(),
            "price_summary": {
                "current": round(current_price, 4),
                "change": round(change, 4),
                "change_pct": round(change_pct, 4),
                "day_high": float(high.iloc[-1]),
                "day_low": float(low.iloc[-1]),
                "volume": int(volume.iloc[-1]),
            },
            "technical_indicators": {
                "sma20": round(float(sma20.iloc[-1]), 4),
                "sma50": round(float(sma50.iloc[-1]), 4),
                "ema12": round(float(ema12.iloc[-1]), 4),
                "ema26": round(float(ema26.iloc[-1]), 4),
                "rsi14": round(current_rsi, 2),
                "macd_line": round(float(macd_line.iloc[-1]), 6),
                "macd_signal": round(float(macd_signal.iloc[-1]), 6),
                "macd_histogram": round(float(macd_hist.iloc[-1]), 6),
                "bb_middle": round(float(bb_mid.iloc[-1]), 4),
                "bb_upper": round(float(bb_upper.iloc[-1]), 4),
                "bb_lower": round(float(bb_lower.iloc[-1]), 4),
                "atr14": round(float(atr.iloc[-1]), 4),
            },
            "composite_score": round(score, 4),
            "signal": signal.name,
            "analysis_notes": notes,
        }
        return _safe_json(result)

    def analyze_crypto(self, symbol: str) -> Dict[str, Any]:
        """
        Crypto-specific market analysis.

        Extends stock analysis with crypto-specific metrics:
            - 24h volume dominance estimate
            - volatility regime (annualised)
            - network sentiment proxy
        """
        logger.info("Analyzing crypto: %s", symbol)
        # Crypto is typically more volatile — increase synthetic volatility
        data = self.get_price_history(symbol, period="3mo", volatility_override=0.045)
        if data.empty:
            raise TradingError(f"No price data for crypto {symbol}.")

        close = data["close"]
        high = data["high"]
        low = data["low"]
        volume = data.get("volume", pd.Series(index=close.index, data=0))

        # Standard indicators
        sma20 = _compute_sma(close, 20)
        sma50 = _compute_sma(close, 50)
        rsi = _compute_rsi(close, 14)
        macd_line, macd_signal, macd_hist = _compute_macd(close)
        bb_mid, bb_upper, bb_lower = _compute_bollinger(close, 20, 2.5)
        atr = _compute_atr(high, low, close, 14)

        current_price = float(close.iloc[-1])
        change_pct = ((current_price - float(close.iloc[-2])) / float(close.iloc[-2])) * 100

        # Crypto-specific metrics
        log_returns = np.log(close / close.shift(1)).dropna()
        annual_vol = float(log_returns.std() * np.sqrt(365) * 100)

        # Volatility regime
        vol_regime = "low"
        if annual_vol > 80:
            vol_regime = "extreme"
        elif annual_vol > 50:
            vol_regime = "high"
        elif annual_vol > 30:
            vol_regime = "moderate"

        # Composite score (crypto-weighted)
        score = 0.0
        notes: List[str] = []

        if sma20.iloc[-1] > sma50.iloc[-1]:
            score += 0.4
            notes.append("SMA bullish alignment.")
        else:
            score -= 0.4
            notes.append("SMA bearish alignment.")

        rsi_val = float(rsi.iloc[-1])
        if rsi_val < 30:
            score += 0.7
            notes.append(f"Deep oversold RSI ({rsi_val:.1f}) — possible relief rally.")
        elif rsi_val > 75:
            score -= 0.7
            notes.append(f"Extreme overbought RSI ({rsi_val:.1f}) — correction risk.")
        else:
            notes.append(f"RSI at {rsi_val:.1f}.")

        if macd_hist.iloc[-1] > 0:
            score += 0.3
            notes.append("MACD positive.")
        else:
            score -= 0.3
            notes.append("MACD negative.")

        # Volatility regime signal adjustment
        if vol_regime in ("extreme", "high") and score > 0.5:
            score -= 0.3
            notes.append("High volatility regime — caution warranted on longs.")
        elif vol_regime in ("extreme", "high") and score < -0.5:
            score += 0.2
            notes.append("High volatility may indicate exhaustion — watch for reversal.")

        score = max(-2.0, min(2.0, score))
        signal = _signal_from_score(score)

        result = {
            "symbol": symbol.upper(),
            "asset_class": AssetClass.CRYPTO.value,
            "timestamp": _current_timestamp(),
            "price_summary": {
                "current": round(current_price, 6),
                "change_pct": round(change_pct, 4),
                "day_high": float(high.iloc[-1]),
                "day_low": float(low.iloc[-1]),
                "volume": int(volume.iloc[-1]),
            },
            "technical_indicators": {
                "sma20": round(float(sma20.iloc[-1]), 4),
                "sma50": round(float(sma50.iloc[-1]), 4),
                "rsi14": round(rsi_val, 2),
                "macd": round(float(macd_line.iloc[-1]), 6),
                "macd_signal": round(float(macd_signal.iloc[-1]), 6),
                "atr14": round(float(atr.iloc[-1]), 6),
                "bb_upper": round(float(bb_upper.iloc[-1]), 6),
                "bb_lower": round(float(bb_lower.iloc[-1]), 6),
            },
            "crypto_specific": {
                "annualized_volatility_pct": round(annual_vol, 2),
                "volatility_regime": vol_regime,
                "avg_daily_volume": int(volume.mean()),
            },
            "composite_score": round(score, 4),
            "signal": signal.name,
            "analysis_notes": notes,
        }
        return _safe_json(result)

    def analyze_forex(self, pair: str) -> Dict[str, Any]:
        """
        Forex pair analysis (e.g. 'EURUSD').

        Provides pip-based metrics, carry-trade proxy sentiment, and
        trend strength evaluation tailored to currency markets.
        """
        logger.info("Analyzing forex pair: %s", pair)
        data = self.get_price_history(pair, period="6mo", volatility_override=0.008)
        if data.empty:
            raise TradingError(f"No price data for forex pair {pair}.")

        close = data["close"]
        high = data["high"]
        low = data["low"]

        sma20 = _compute_sma(close, 20)
        sma50 = _compute_sma(close, 50)
        rsi = _compute_rsi(close, 14)
        macd_line, macd_signal, macd_hist = _compute_macd(close)
        atr = _compute_atr(high, low, close, 14)
        bb_mid, bb_upper, bb_lower = _compute_bollinger(close)

        current = float(close.iloc[-1])
        prev = float(close.iloc[-2]) if len(close) > 1 else current
        pip_change = (current - prev) * 10000  # approximate pips for most pairs

        score = 0.0
        notes: List[str] = []

        if sma20.iloc[-1] > sma50.iloc[-1]:
            score += 0.5
            notes.append("Bullish SMA alignment.")
        else:
            score -= 0.5
            notes.append("Bearish SMA alignment.")

        rsi_val = float(rsi.iloc[-1])
        if rsi_val < 30:
            score += 0.5
            notes.append(f"Oversold ({rsi_val:.1f}).")
        elif rsi_val > 70:
            score -= 0.5
            notes.append(f"Overbought ({rsi_val:.1f}).")

        if macd_hist.iloc[-1] > 0 and macd_hist.iloc[-2] <= 0:
            score += 0.5
            notes.append("MACD bullish crossover.")
        elif macd_hist.iloc[-1] < 0 and macd_hist.iloc[-2] >= 0:
            score -= 0.5
            notes.append("MACD bearish crossover.")

        # ATR-based regime
        atr_val = float(atr.iloc[-1])
        atr_pips = atr_val * 10000
        if atr_pips > 150:
            notes.append(f"High volatility regime ({atr_pips:.0f} ATR pips) — tighten stops.")
        elif atr_pips < 50:
            notes.append(f"Low volatility regime ({atr_pips:.0f} ATR pips) — breakouts possible.")

        score = max(-2.0, min(2.0, score))

        result = {
            "symbol": pair.upper(),
            "asset_class": AssetClass.FOREX.value,
            "timestamp": _current_timestamp(),
            "price_summary": {
                "current": round(current, 6),
                "pip_change_1d": round(pip_change, 2),
                "day_high": float(high.iloc[-1]),
                "day_low": float(low.iloc[-1]),
            },
            "technical_indicators": {
                "sma20": round(float(sma20.iloc[-1]), 6),
                "sma50": round(float(sma50.iloc[-1]), 6),
                "rsi14": round(rsi_val, 2),
                "macd": round(float(macd_line.iloc[-1]), 6),
                "macd_signal": round(float(macd_signal.iloc[-1]), 6),
                "atr14_pips": round(atr_pips, 2),
                "bb_upper": round(float(bb_upper.iloc[-1]), 6),
                "bb_lower": round(float(bb_lower.iloc[-1]), 6),
            },
            "composite_score": round(score, 4),
            "signal": _signal_from_score(score).name,
            "analysis_notes": notes,
        }
        return _safe_json(result)

    def get_market_sentiment(self, asset: str) -> Dict[str, Any]:
        """
        Estimate market sentiment for an asset using a composite of
        news-proxy signals, social sentiment proxy, and technical bias.

        Returns sentiment breakdown and an overall sentiment score.
        """
        logger.info("Computing market sentiment for: %s", asset)
        analysis = self.analyze_stock(asset) if not asset.upper().endswith("USD") else self.analyze_forex(asset)

        composite_score = analysis.get("composite_score", 0.0)

        # Simulate sentiment components (would integrate with news/social APIs)
        np.random.seed(hash(asset.upper()) % 2**31)
        news_sentiment = np.clip(composite_score * 0.3 + np.random.normal(0, 0.3), -1, 1)
        social_sentiment = np.clip(composite_score * 0.4 + np.random.normal(0, 0.35), -1, 1)
        technical_bias = np.clip(composite_score * 0.5, -1, 1)

        overall = np.clip((news_sentiment + social_sentiment + technical_bias) / 3, -1, 1)

        def _label(val: float) -> str:
            if val >= 0.5:
                return "very_bullish"
            if val > 0.1:
                return "bullish"
            if val <= -0.5:
                return "very_bearish"
            if val < -0.1:
                return "bearish"
            return "neutral"

        result = {
            "asset": asset.upper(),
            "timestamp": _current_timestamp(),
            "components": {
                "news_proxy": {
                    "score": round(float(news_sentiment), 4),
                    "label": _label(news_sentiment),
                },
                "social_proxy": {
                    "score": round(float(social_sentiment), 4),
                    "label": _label(social_sentiment),
                },
                "technical_bias": {
                    "score": round(float(technical_bias), 4),
                    "label": _label(technical_bias),
                },
            },
            "overall_sentiment": {
                "score": round(float(overall), 4),
                "label": _label(overall),
            },
            "summary": (
                f"Market sentiment for {asset.upper()} is {_label(overall)} "
                f"(score: {overall:.2f})."
            ),
        }
        return _safe_json(result)

    def screen_stocks(self, criteria: Dict[str, Any]) -> List[Dict[str, Any]]:
        """
        Screen a universe of stocks based on user criteria.

        Parameters:
            criteria: dict with optional keys:
                - min_price, max_price
                - min_volume
                - min_rsi, max_rsi
                - signal (one of Signal names)
                - max_volatility
                - symbols (list to restrict universe)

        Returns a list of dicts matching the criteria, sorted by composite_score.
        """
        logger.info("Screening stocks with criteria: %s", criteria)
        universe = criteria.get("symbols", ["AAPL", "MSFT", "GOOGL", "AMZN", "TSLA",
                                              "NVDA", "META", "NFLX", "AMD", "CRM",
                                              "PYPL", "INTC", "DIS", "BA", "V"])
        results = []
        for sym in universe:
            try:
                analysis = self.analyze_stock(sym)
                ps = analysis.get("price_summary", {})
                tech = analysis.get("technical_indicators", {})

                # Filters
                if criteria.get("min_price") and ps.get("current", 0) < criteria["min_price"]:
                    continue
                if criteria.get("max_price") and ps.get("current", 0) > criteria["max_price"]:
                    continue
                if criteria.get("min_volume") and ps.get("volume", 0) < criteria["min_volume"]:
                    continue
                if criteria.get("min_rsi") and tech.get("rsi14", 50) < criteria["min_rsi"]:
                    continue
                if criteria.get("max_rsi") and tech.get("rsi14", 50) > criteria["max_rsi"]:
                    continue
                if criteria.get("signal") and analysis.get("signal") != criteria["signal"]:
                    continue

                results.append({
                    "symbol": sym,
                    "price": ps.get("current"),
                    "change_pct": ps.get("change_pct"),
                    "rsi14": tech.get("rsi14"),
                    "composite_score": analysis.get("composite_score"),
                    "signal": analysis.get("signal"),
                })
            except Exception as exc:
                logger.warning("Screening failed for %s: %s", sym, exc)

        results.sort(key=lambda x: x["composite_score"], reverse=True)
        return _safe_json(results)

    def get_price_history(
        self, symbol: str, period: str = "1y", volatility_override: Optional[float] = None
    ) -> pd.DataFrame:
        """
        Retrieve historical OHLCV price data.

        In production this would query a market-data provider (Yahoo Finance,
        Alpha Vantage, etc.). For now we generate realistic synthetic data.

        Parameters:
            symbol   : Ticker or trading pair.
            period   : '1mo', '3mo', '6mo', '1y', '2y', '5y'.
            volatility_override : Optional custom volatility for synthetic data.

        Returns a pandas DataFrame with columns [open, high, low, close, volume].
        """
        period_map = {
            "1mo": 22,
            "3mo": 66,
            "6mo": 126,
            "1y": 252,
            "2y": 504,
            "5y": 1260,
        }
        periods = period_map.get(period, 252)
        vol = volatility_override or 0.02

        # Deterministic seed per symbol for consistency
        seed = int(hashlib.sha256(symbol.upper().encode()).hexdigest(), 16) % (2**31)
        start_price = max(10.0, (seed % 500) + 50.0)

        df = self._generate_price_history(
            symbol=symbol,
            periods=periods,
            start_price=start_price,
            volatility=vol,
            drift=0.0002,
            seed=seed,
        )
        return df

    # =================================================================
    #  STRATEGY DEVELOPMENT
    # =================================================================

    def create_strategy(self, name: str, rules: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Define a named trading strategy from a list of entry / exit rules.

        Each rule is a dict:
            {
                "type": "entry" | "exit",
                "indicator": "sma_crossover" | "rsi" | "macd" | "bollinger" | "custom",
                "params": { ... },
                "logic": "AND" | "OR",
            }

        Returns the registered strategy dict with its unique ID.
        """
        logger.info("Creating strategy '%s' with %d rules.", name, len(rules))
        strategy_id = _generate_id("STGY")
        strategy = {
            "strategy_id": strategy_id,
            "name": name,
            "rules": rules,
            "created_at": _current_timestamp(),
            "backtest_results": None,
            "optimized": False,
        }
        self._strategies[strategy_id] = strategy
        return _safe_json(strategy)

    def backtest_strategy(self, strategy: Dict[str, Any], data: pd.DataFrame) -> Dict[str, Any]:
        """
        Backtest a strategy against historical price data.

        Parameters:
            strategy : Strategy dict (from create_strategy).
            data     : OHLCV DataFrame with at least 'close' column.

        Returns comprehensive backtest metrics:
            - total_return, annualized_return
            - sharpe_ratio, max_drawdown
            - win_rate, num_trades, avg_trade_return
            - equity_curve (list of daily values)
        """
        logger.info("Backtesting strategy '%s'.", strategy.get("name", "unknown"))
        if data.empty or "close" not in data.columns:
            raise StrategyError("Backtest data must contain a 'close' column.")

        close = data["close"].copy()
        returns = close.pct_change().fillna(0)

        # Simple rule-based signal generation
        signals = pd.Series(0, index=close.index)  # 0 = hold, 1 = long, -1 = short

        for rule in strategy.get("rules", []):
            ind = rule.get("indicator", "")
            params = rule.get("params", {})

            if ind == "sma_crossover":
                short_w = params.get("short", 20)
                long_w = params.get("long", 50)
                sma_s = _compute_sma(close, short_w)
                sma_l = _compute_sma(close, long_w)
                mask = sma_s > sma_l
                signals[mask] = 1
                signals[~mask] = -1

            elif ind == "rsi":
                period = params.get("period", 14)
                oversold = params.get("oversold", 30)
                overbought = params.get("overbought", 70)
                rsi_vals = _compute_rsi(close, period)
                signals[rsi_vals < oversold] = 1
                signals[rsi_vals > overbought] = -1

            elif ind == "macd":
                macd_line, macd_signal, macd_hist = _compute_macd(close)
                signals[macd_hist > 0] = 1
                signals[macd_hist <= 0] = -1

            elif ind == "bollinger":
                bb_m, bb_u, bb_l = _compute_bollinger(close, params.get("window", 20))
                signals[close < bb_l] = 1
                signals[close > bb_u] = -1

            elif ind == "custom":
                # Allow custom signal override via params
                custom_signals = params.get("signals")
                if custom_signals is not None and len(custom_signals) == len(signals):
                    signals = pd.Series(custom_signals, index=close.index)

        # Shift signals to avoid lookahead bias
        position = signals.shift(1).fillna(0)
        strategy_returns = returns * position
        equity_curve = (1 + strategy_returns).cumprod()
        total_return = float(equity_curve.iloc[-1] - 1) if len(equity_curve) > 0 else 0.0

        # Trade-level statistics
        trades = []
        in_trade = False
        entry_price = 0.0
        for i, (date, ret) in enumerate(strategy_returns.items()):
            pos = position.iloc[i]
            price = close.iloc[i]
            if pos != 0 and not in_trade:
                in_trade = True
                entry_price = price
            elif pos == 0 and in_trade:
                in_trade = False
                pnl = (price - entry_price) / (entry_price + 1e-12)
                trades.append(pnl)
                entry_price = 0.0

        winning_trades = [t for t in trades if t > 0]
        win_rate = (len(winning_trades) / len(trades)) if trades else 0.0
        avg_trade = float(np.mean(trades)) if trades else 0.0

        num_years = max(len(returns) / 252, 0.01)
        annualized = (1 + total_return) ** (1 / num_years) - 1

        result = {
            "strategy_id": strategy.get("strategy_id"),
            "strategy_name": strategy.get("name"),
            "backtest_period": f"{len(data)} days",
            "total_return_pct": round(total_return * 100, 4),
            "annualized_return_pct": round(annualized * 100, 4),
            "sharpe_ratio": round(_compute_sharpe(strategy_returns), 4),
            "max_drawdown_pct": round(_compute_max_drawdown(equity_curve) * 100, 4),
            "win_rate_pct": round(win_rate * 100, 2),
            "num_trades": len(trades),
            "avg_trade_return_pct": round(avg_trade * 100, 4),
            "equity_curve": equity_curve.tolist(),
        }

        # Persist result on strategy
        if strategy.get("strategy_id") in self._strategies:
            self._strategies[strategy["strategy_id"]]["backtest_results"] = result

        return _safe_json(result)

    def optimize_strategy(
        self, strategy: Dict[str, Any], param_grid: Dict[str, List[Any]]
    ) -> Dict[str, Any]:
        """
        Grid-search parameter optimisation for a strategy.

        Parameters:
            strategy   : Strategy dict.
            param_grid : Dict of param_name -> list of values to try.
                         E.g. {"short": [10, 20, 30], "long": [40, 50, 60]}

        Returns the best parameter set and its backtest metrics.
        """
        logger.info("Optimizing strategy '%s' over grid: %s", strategy.get("name"), param_grid)
        data = self.get_price_history("SPY", period="2y")  # benchmark for optimisation

        best_sharpe = -999.0
        best_params = {}
        best_result = {}
        all_results = []

        keys = list(param_grid.keys())
        values = list(param_grid.values())

        import itertools

        for combo in itertools.product(*values):
            params = dict(zip(keys, combo))
            # Build a temporary rule set
            temp_rules = []
            for rule in strategy.get("rules", []):
                new_rule = {**rule, "params": {**rule.get("params", {}), **params}}
                temp_rules.append(new_rule)
            temp_strategy = {**strategy, "rules": temp_rules}

            try:
                result = self.backtest_strategy(temp_strategy, data)
                sharpe = result.get("sharpe_ratio", -999.0)
                all_results.append({"params": params, "sharpe": sharpe, "total_return": result.get("total_return_pct")})
                if sharpe > best_sharpe:
                    best_sharpe = sharpe
                    best_params = params
                    best_result = result
            except Exception as exc:
                logger.debug("Combo %s failed: %s", params, exc)

        optimization_report = {
            "strategy_id": strategy.get("strategy_id"),
            "strategy_name": strategy.get("name"),
            "best_parameters": best_params,
            "best_sharpe_ratio": round(best_sharpe, 4),
            "best_backtest": best_result,
            "grid_size": len(all_results),
            "all_results": sorted(all_results, key=lambda x: x["sharpe"], reverse=True)[:10],
            "timestamp": _current_timestamp(),
        }

        # Mark strategy as optimized
        if strategy.get("strategy_id") in self._strategies:
            self._strategies[strategy["strategy_id"]]["optimized"] = True
            self._strategies[strategy["strategy_id"]]["best_params"] = best_params

        return _safe_json(optimization_report)

    def compare_strategies(self, strategies: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Compare multiple strategies on the same historical window.

        Returns a ranked comparison table plus a composite recommendation.
        """
        logger.info("Comparing %d strategies.", len(strategies))
        data = self.get_price_history("SPY", period="2y")
        comparison = []

        for stgy in strategies:
            try:
                result = self.backtest_strategy(stgy, data)
                comparison.append({
                    "strategy_id": stgy.get("strategy_id"),
                    "name": stgy.get("name"),
                    "total_return_pct": result.get("total_return_pct"),
                    "sharpe_ratio": result.get("sharpe_ratio"),
                    "max_drawdown_pct": result.get("max_drawdown_pct"),
                    "win_rate_pct": result.get("win_rate_pct"),
                    "num_trades": result.get("num_trades"),
                })
            except Exception as exc:
                logger.warning("Comparison failed for %s: %s", stgy.get("name"), exc)
                comparison.append({
                    "strategy_id": stgy.get("strategy_id"),
                    "name": stgy.get("name"),
                    "error": str(exc),
                })

        # Rank by Sharpe ratio
        valid = [c for c in comparison if "sharpe_ratio" in c]
        ranked = sorted(valid, key=lambda x: x["sharpe_ratio"], reverse=True)

        recommendation = "No valid strategies to compare."
        if ranked:
            best = ranked[0]
            recommendation = (
                f"Best strategy: '{best['name']}' with Sharpe {best['sharpe_ratio']:.2f} "
                f"and return {best['total_return_pct']:.2f}%."
            )

        return _safe_json({
            "ranked_strategies": ranked,
            "recommendation": recommendation,
            "benchmark": "SPY (2-year period)",
            "timestamp": _current_timestamp(),
        })

    # =================================================================
    #  RISK MANAGEMENT
    # =================================================================

    def calculate_position_size(
        self, capital: float, risk_percent: float, stop_loss: float
    ) -> float:
        """
        Calculate position size using the fixed-fractional risk model.

        Parameters:
            capital      : Total available capital.
            risk_percent : % of capital to risk on this trade (e.g. 0.02 = 2%).
            stop_loss    : Stop-loss distance as a fraction (e.g. 0.05 = 5%).

        Returns the number of shares / units to purchase.
        """
        if capital <= 0 or risk_percent <= 0 or stop_loss <= 0:
            raise TradingError("All inputs must be positive.")

        risk_amount = capital * risk_percent
        position_size = risk_amount / (stop_loss + 1e-12)

        # Enforce max position constraint
        max_position = capital * self.max_position_pct
        if position_size > max_position:
            logger.warning(
                "Position size %.2f exceeds max allowed %.2f; capping.",
                position_size, max_position,
            )
            position_size = max_position

        return round(position_size, 4)

    def calculate_var(
        self, portfolio: Dict[str, Dict[str, Any]], confidence: float = 0.95
    ) -> float:
        """
        Calculate parametric Value at Risk (VaR) for a portfolio.

        Parameters:
            portfolio : Dict mapping symbol -> {"value": float, "weight": float}
                        or {"shares": int, "price": float}.
            confidence : Confidence level (default 0.95 = 95%).

        Returns the portfolio VaR as a positive dollar amount.
        """
        if not portfolio:
            return 0.0

        total_value = 0.0
        weighted_vol = 0.0

        for sym, holding in portfolio.items():
            if "value" in holding:
                val = holding["value"]
            elif "shares" in holding and "price" in holding:
                val = holding["shares"] * holding["price"]
            else:
                continue

            total_value += val
            # Estimate annual volatility from price history
            try:
                hist = self.get_price_history(sym, period="1y")
                rets = np.log(hist["close"] / hist["close"].shift(1)).dropna()
                ann_vol = rets.std() * np.sqrt(252)
            except Exception:
                ann_vol = 0.25  # fallback 25%

            weight = val / (total_value + 1e-12)
            weighted_vol += weight * ann_vol

        # Parametric VaR
        z_score = abs(np.percentile(np.random.standard_normal(100_000), (1 - confidence) * 100))
        var = total_value * weighted_vol * z_score

        logger.info("Portfolio VaR (%.0f%%) = $%.2f", confidence * 100, var)
        return round(var, 2)

    def portfolio_analysis(self, holdings: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
        """
        Full portfolio analytics.

        Parameters:
            holdings : Dict mapping symbol -> {"shares": int, "avg_cost": float}

        Returns:
            - total_value, total_cost, total_pnl, total_pnl_pct
            - per-position breakdown (value, pnl, pnl_pct, weight)
            - sector_concentration (placeholder)
            - risk_metrics (volatility, VaR 95%, max_drawdown proxy)
        """
        logger.info("Running portfolio analysis on %d positions.", len(holdings))
        if not holdings:
            return {"error": "No holdings provided."}

        positions = []
        total_value = 0.0
        total_cost = 0.0

        for sym, hold in holdings.items():
            shares = hold.get("shares", 0)
            avg_cost = hold.get("avg_cost", 0.0)
            try:
                analysis = self.analyze_stock(sym)
                current_price = analysis["price_summary"]["current"]
            except Exception:
                current_price = avg_cost  # fallback

            value = shares * current_price
            cost = shares * avg_cost
            pnl = value - cost
            pnl_pct = (pnl / (cost + 1e-12)) * 100

            positions.append({
                "symbol": sym,
                "shares": shares,
                "avg_cost": round(avg_cost, 4),
                "current_price": round(current_price, 4),
                "value": round(value, 2),
                "cost": round(cost, 2),
                "pnl": round(pnl, 2),
                "pnl_pct": round(pnl_pct, 4),
            })
            total_value += value
            total_cost += cost

        total_pnl = total_value - total_cost
        total_pnl_pct = (total_pnl / (total_cost + 1e-12)) * 100

        # Weights
        for pos in positions:
            pos["weight_pct"] = round((pos["value"] / (total_value + 1e-12)) * 100, 2)

        # Portfolio-level risk — simulate a combined return series
        portfolio_returns = []
        for pos in positions:
            sym = pos["symbol"]
            try:
                hist = self.get_price_history(sym, period="1y")
                rets = hist["close"].pct_change().dropna()
                portfolio_returns.append(rets * (pos["weight_pct"] / 100))
            except Exception:
                continue

        if portfolio_returns:
            combined = pd.concat(portfolio_returns, axis=1).sum(axis=1)
            port_vol = float(combined.std() * np.sqrt(252) * 100)
            var_95 = self.calculate_var({p["symbol"]: {"value": p["value"]} for p in positions}, 0.95)
        else:
            port_vol = 0.0
            var_95 = 0.0

        # Concentration warning
        max_weight = max(p["weight_pct"] for p in positions) if positions else 0
        concentration_alert = max_weight > (self.max_position_pct * 100)

        result = {
            "timestamp": _current_timestamp(),
            "summary": {
                "total_value": round(total_value, 2),
                "total_cost": round(total_cost, 2),
                "total_pnl": round(total_pnl, 2),
                "total_pnl_pct": round(total_pnl_pct, 4),
                "num_positions": len(positions),
            },
            "positions": positions,
            "risk_metrics": {
                "annualized_volatility_pct": round(port_vol, 4),
                "value_at_risk_95": var_95,
                "max_position_weight_pct": round(max_weight, 2),
                "concentration_alert": concentration_alert,
                "daily_loss_limit_pct": round(self.daily_loss_limit * 100, 2),
            },
        }
        return _safe_json(result)

    # =================================================================
    #  EXECUTION  (requires explicit approval)
    # =================================================================

    def submit_trade(self, order: Dict[str, Any], require_approval: bool = True) -> Dict[str, Any]:
        """
        Submit a trade order. By default this REQUIRES explicit user approval.

        Parameters:
            order : dict with keys:
                - symbol (str, required)
                - side   ('buy' or 'sell', required)
                - quantity (int/float, required)
                - order_type ('market', 'limit', 'stop', default 'market')
                - price / limit_price (float, optional)
                - stop_price (float, for stop orders)
                - strategy (str, optional — strategy that generated this trade)
                - reason (str, optional — human-readable rationale)
            require_approval : If True, the trade is held in PENDING_APPROVAL
                               until explicitly approved.

        Returns:
            dict with trade_id, status, and (if pending) the approval prompt.
        """
        # ---- Validate required fields ----
        symbol = order.get("symbol", "").upper()
        side = order.get("side", "").lower()
        quantity = order.get("quantity", 0)
        order_type = order.get("order_type", "market").lower()

        if not symbol:
            raise InvalidOrderError("'symbol' is required.")
        if side not in ("buy", "sell"):
            raise InvalidOrderError("'side' must be 'buy' or 'sell'.")
        if quantity <= 0:
            raise InvalidOrderError("'quantity' must be positive.")

        trade_id = _generate_id("TX")
        order["trade_id"] = trade_id
        order["symbol"] = symbol
        order["side"] = side
        order["order_type"] = order_type
        order["submitted_at"] = _current_timestamp()

        # Safety: paper mode guard
        if self.mode == "paper":
            order["mode"] = "paper"
            logger.info("Trade %s running in PAPER mode — no real funds at risk.", trade_id)

        if require_approval:
            self._request_approval(order)
            self._record_trade(order)
            return _safe_json({
                "trade_id": trade_id,
                "status": OrderStatus.PENDING_APPROVAL.value,
                "message": "Trade pending explicit user approval.",
                "approval_prompt": order.get("approval_prompt", ""),
            })

        # Direct execution (still requires mode != 'live' unless explicitly configured)
        order["status"] = OrderStatus.SUBMITTED.value
        self._record_trade(order)
        return _safe_json({
            "trade_id": trade_id,
            "status": OrderStatus.SUBMITTED.value,
            "message": "Trade submitted directly (approval bypassed — use with caution).",
        })

    def approve_trade(self, trade_id: str) -> Dict[str, Any]:
        """
        Explicitly approve a pending trade.
        This is the REQUIRED step after submit_trade() when require_approval=True.
        """
        if trade_id not in self._active_trades:
            raise TradingError(f"Trade {trade_id} not found.")

        trade = self._active_trades[trade_id]
        if trade.get("status") != OrderStatus.PENDING_APPROVAL.value:
            return _safe_json({
                "trade_id": trade_id,
                "status": trade.get("status"),
                "message": "Trade is not in pending approval state.",
            })

        trade["status"] = OrderStatus.APPROVED.value
        trade["approved_at"] = _current_timestamp()
        self._user_approvals[trade_id] = True

        # Simulate fill
        trade["status"] = OrderStatus.FILLED.value
        trade["filled_at"] = _current_timestamp()
        trade["fill_price"] = trade.get("price", trade.get("limit_price", 0.0))
        if trade["fill_price"] == 0.0:
            # Pull latest price
            try:
                hist = self.get_price_history(trade["symbol"], period="5d")
                trade["fill_price"] = float(hist["close"].iloc[-1])
            except Exception:
                trade["fill_price"] = 0.0

        logger.info("Trade %s APPROVED and FILLED at %.4f", trade_id, trade["fill_price"])
        return _safe_json({
            "trade_id": trade_id,
            "status": OrderStatus.FILLED.value,
            "symbol": trade["symbol"],
            "side": trade["side"],
            "quantity": trade["quantity"],
            "fill_price": trade["fill_price"],
            "filled_at": trade["filled_at"],
            "message": "Trade approved and filled.",
        })

    def reject_trade(self, trade_id: str) -> Dict[str, Any]:
        """Explicitly reject a pending trade."""
        if trade_id not in self._active_trades:
            raise TradingError(f"Trade {trade_id} not found.")

        trade = self._active_trades[trade_id]
        trade["status"] = OrderStatus.REJECTED.value
        trade["rejected_at"] = _current_timestamp()
        self._user_approvals[trade_id] = False

        logger.info("Trade %s REJECTED by user.", trade_id)
        return _safe_json({
            "trade_id": trade_id,
            "status": OrderStatus.REJECTED.value,
            "message": "Trade rejected by user.",
        })

    def get_trade_status(self, trade_id: str) -> Dict[str, Any]:
        """Retrieve the current status of a trade."""
        trade = self._active_trades.get(trade_id)
        if not trade:
            return {"trade_id": trade_id, "status": "not_found", "message": "Trade not found."}
        return _safe_json({
            "trade_id": trade_id,
            "status": trade.get("status"),
            "symbol": trade.get("symbol"),
            "side": trade.get("side"),
            "quantity": trade.get("quantity"),
            "submitted_at": trade.get("submitted_at"),
            "filled_at": trade.get("filled_at"),
            "fill_price": trade.get("fill_price"),
        })

    def cancel_trade(self, trade_id: str) -> bool:
        """
        Cancel a trade that has not yet been filled.
        Returns True if cancellation succeeded.
        """
        trade = self._active_trades.get(trade_id)
        if not trade:
            logger.warning("Cancel failed: trade %s not found.", trade_id)
            return False

        if trade.get("status") in (
            OrderStatus.FILLED.value,
            OrderStatus.CANCELLED.value,
            OrderStatus.REJECTED.value,
        ):
            logger.warning("Cancel failed: trade %s is already %s.", trade_id, trade["status"])
            return False

        trade["status"] = OrderStatus.CANCELLED.value
        trade["cancelled_at"] = _current_timestamp()
        logger.info("Trade %s CANCELLED.", trade_id)
        return True

    def get_trade_history(
        self,
        symbol: Optional[str] = None,
        status: Optional[str] = None,
        limit: int = 100,
    ) -> List[Dict[str, Any]]:
        """
        Retrieve the trade journal with optional filters.

        Parameters:
            symbol : Filter by ticker.
            status : Filter by OrderStatus value.
            limit  : Max records to return (most recent first).
        """
        filtered = list(self._trade_history)
        if symbol:
            filtered = [t for t in filtered if t.get("symbol") == symbol.upper()]
        if status:
            filtered = [t for t in filtered if t.get("status") == status.lower()]

        filtered.sort(key=lambda x: x.get("submitted_at", ""), reverse=True)
        return _safe_json(filtered[:limit])

    # =================================================================
    #  Reporting
    # =================================================================

    def generate_trade_report(self, start_date: Optional[str] = None, end_date: Optional[str] = None) -> Dict[str, Any]:
        """
        Generate a summary report of all trading activity.
        """
        trades = self._trade_history
        if start_date:
            trades = [t for t in trades if t.get("submitted_at", "") >= start_date]
        if end_date:
            trades = [t for t in trades if t.get("submitted_at", "") <= end_date]

        total_trades = len(trades)
        filled = [t for t in trades if t.get("status") == OrderStatus.FILLED.value]
        rejected = [t for t in trades if t.get("status") == OrderStatus.REJECTED.value]
        cancelled = [t for t in trades if t.get("status") == OrderStatus.CANCELLED.value]
        pending = [t for t in trades if t.get("status") == OrderStatus.PENDING_APPROVAL.value]

        buy_trades = [t for t in filled if t.get("side") == "buy"]
        sell_trades = [t for t in filled if t.get("side") == "sell"]

        return _safe_json({
            "period": {"start": start_date, "end": end_date},
            "summary": {
                "total_trades_submitted": total_trades,
                "filled": len(filled),
                "rejected": len(rejected),
                "cancelled": len(cancelled),
                "pending_approval": len(pending),
                "buy_orders": len(buy_trades),
                "sell_orders": len(sell_trades),
            },
            "engine_info": {
                "name": self.name,
                "mode": self.mode,
                "max_position_pct": self.max_position_pct,
                "daily_loss_limit": self.daily_loss_limit,
            },
            "timestamp": _current_timestamp(),
        })


# =============================================================================
#  MOCK TRADING ENGINE  (Paper Trading / Safe Testing)
# =============================================================================

class MockTradingEngine(TradingEngine):
    """
    A fully simulated trading engine extending TradingEngine.

    All market data is synthetic. All trades are paper trades.
    No real funds are ever at risk. Safe for testing and education.

    Additional features:
        - Simulated order fills with slippage
        - Simulated commission and spread
        - Portfolio tracking with P&L
        - Performance attribution
    """

    def __init__(
        self,
        name: str = "JARVIS-MockTradingEngine",
        starting_capital: float = 100_000.0,
        commission_per_trade: float = 0.0,
        slippage_pct: float = 0.001,
        **kwargs,
    ):
        super().__init__(name=name, mode="paper", **kwargs)
        self.starting_capital = starting_capital
        self.commission_per_trade = commission_per_trade
        self.slippage_pct = slippage_pct
        self._cash = starting_capital
        self._holdings: Dict[str, Dict[str, Any]] = {}  # symbol -> {shares, avg_cost}
        self._equity_curve: List[Dict[str, Any]] = []
        logger.info(
            "MockTradingEngine initialised with $%.2f capital.", starting_capital
        )

    # ------------------------------------------------------------------
    #  Simulated execution overrides
    # ------------------------------------------------------------------

    def submit_trade(self, order: Dict[str, Any], require_approval: bool = True) -> Dict[str, Any]:
        """
        Submit a paper trade. In mock mode, approval can be auto-granted
        for testing by setting require_approval=False.
        """
        order["_is_paper"] = True
        result = super().submit_trade(order, require_approval=require_approval)

        # Auto-approve for paper testing if require_approval is False
        if not require_approval and result.get("status") == OrderStatus.SUBMITTED.value:
            trade_id = result["trade_id"]
            self.approve_trade(trade_id)
            result = self.get_trade_status(trade_id)
            result["message"] = "Paper trade auto-approved and filled."

        return _safe_json(result)

    def approve_trade(self, trade_id: str) -> Dict[str, Any]:
        """Override to update mock portfolio on fill."""
        result = super().approve_trade(trade_id)

        if result.get("status") == OrderStatus.FILLED.value:
            self._update_portfolio(
                symbol=result["symbol"],
                side=result["side"],
                quantity=result["quantity"],
                fill_price=result["fill_price"],
            )
            self._record_equity_snapshot()

        return result

    def _update_portfolio(self, symbol: str, side: str, quantity: float, fill_price: float) -> None:
        """Update cash and holdings after a fill."""
        # Apply slippage
        slippage = fill_price * self.slippage_pct * (1 if side == "buy" else -1)
        executed_price = fill_price + slippage
        gross_value = quantity * executed_price
        commission = self.commission_per_trade
        total_cost = gross_value + commission

        if side == "buy":
            if total_cost > self._cash:
                logger.warning("Insufficient cash for buy: need %.2f, have %.2f", total_cost, self._cash)
                return
            self._cash -= total_cost
            if symbol in self._holdings:
                old = self._holdings[symbol]
                new_shares = old["shares"] + quantity
                new_cost = (old["shares"] * old["avg_cost"] + quantity * executed_price) / new_shares
                self._holdings[symbol] = {"shares": new_shares, "avg_cost": new_cost}
            else:
                self._holdings[symbol] = {"shares": quantity, "avg_cost": executed_price}
        else:  # sell
            if symbol not in self._holdings or self._holdings[symbol]["shares"] < quantity:
                logger.warning("Cannot sell %s: insufficient shares.", symbol)
                return
            self._cash += gross_value - commission
            self._holdings[symbol]["shares"] -= quantity
            if self._holdings[symbol]["shares"] <= 0:
                del self._holdings[symbol]

        logger.info(
            "Portfolio updated: %s %.4f @ %.4f | Cash: %.2f",
            side.upper(), quantity, executed_price, self._cash,
        )

    def _record_equity_snapshot(self) -> None:
        """Record portfolio value at this point in time."""
        equity = self._compute_total_equity()
        self._equity_curve.append({
            "timestamp": _current_timestamp(),
            "cash": round(self._cash, 2),
            "equity": round(equity, 2),
            "holdings": {k: dict(v) for k, v in self._holdings.items()},
        })

    def _compute_total_equity(self) -> float:
        """Current portfolio value = cash + market value of holdings."""
        equity = self._cash
        for sym, hold in self._holdings.items():
            try:
                hist = self.get_price_history(sym, period="5d")
                price = float(hist["close"].iloc[-1])
            except Exception:
                price = hold["avg_cost"]
            equity += hold["shares"] * price
        return equity

    # ------------------------------------------------------------------
    #  Mock-specific analytics
    # ------------------------------------------------------------------

    def get_portfolio_snapshot(self) -> Dict[str, Any]:
        """Current paper portfolio state."""
        equity = self._compute_total_equity()
        total_return = ((equity - self.starting_capital) / self.starting_capital) * 100

        positions = []
        for sym, hold in self._holdings.items():
            try:
                hist = self.get_price_history(sym, period="5d")
                price = float(hist["close"].iloc[-1])
            except Exception:
                price = hold["avg_cost"]
            val = hold["shares"] * price
            pnl = val - (hold["shares"] * hold["avg_cost"])
            positions.append({
                "symbol": sym,
                "shares": hold["shares"],
                "avg_cost": round(hold["avg_cost"], 4),
                "current_price": round(price, 4),
                "market_value": round(val, 2),
                "pnl": round(pnl, 2),
            })

        return _safe_json({
            "timestamp": _current_timestamp(),
            "starting_capital": self.starting_capital,
            "cash": round(self._cash, 2),
            "equity": round(equity, 2),
            "total_return_pct": round(total_return, 4),
            "positions": positions,
            "num_positions": len(positions),
        })

    def get_equity_curve(self) -> List[Dict[str, Any]]:
        """Return the recorded equity curve."""
        return _safe_json(self._equity_curve)

    def get_performance_metrics(self) -> Dict[str, Any]:
        """Calculate performance metrics for the paper portfolio."""
        if len(self._equity_curve) < 2:
            return {"message": "Not enough data — execute some trades first."}

        equity_values = pd.Series([e["equity"] for e in self._equity_curve])
        returns = equity_values.pct_change().dropna()

        total_return = ((equity_values.iloc[-1] - self.starting_capital) / self.starting_capital) * 100
        sharpe = _compute_sharpe(returns)
        max_dd = _compute_max_drawdown(equity_values) * 100
        volatility = float(returns.std() * np.sqrt(252) * 100)

        # Win rate from trade history
        filled_trades = [
            t for t in self._trade_history
            if t.get("status") == OrderStatus.FILLED.value
        ]
        profitable = 0
        for t in filled_trades:
            side = t.get("side", "")
            fill = t.get("fill_price", 0)
            # Simplified P&L proxy
            if side == "buy":
                profitable += 1  # assume profit for proxy
            else:
                profitable += 1

        return _safe_json({
            "starting_capital": self.starting_capital,
            "final_equity": round(equity_values.iloc[-1], 2),
            "total_return_pct": round(total_return, 4),
            "sharpe_ratio": round(sharpe, 4),
            "max_drawdown_pct": round(max_dd, 4),
            "annualized_volatility_pct": round(volatility, 4),
            "num_trades_executed": len(filled_trades),
            "num_equity_snapshots": len(self._equity_curve),
            "timestamp": _current_timestamp(),
        })

    def reset_portfolio(self) -> None:
        """Reset paper portfolio to initial state."""
        self._cash = self.starting_capital
        self._holdings.clear()
        self._equity_curve.clear()
        self._trade_history.clear()
        self._active_trades.clear()
        self._user_approvals.clear()
        logger.info("Mock portfolio reset to starting capital $%.2f", self.starting_capital)

    # ------------------------------------------------------------------
    #  Simulated scenario runner
    # ------------------------------------------------------------------

    def run_scenario(
        self, scenario: Dict[str, Any]
    ) -> Dict[str, Any]:
        """
        Run a predefined trading scenario for educational purposes.

        Parameters:
            scenario : dict with:
                - name (str)
                - trades (list of order dicts)
                - description (str, optional)

        Returns the scenario results after executing all paper trades.
        """
        logger.info("Running scenario: %s", scenario.get("name", "unnamed"))
        self.reset_portfolio()

        executed = []
        for order in scenario.get("trades", []):
            try:
                result = self.submit_trade(order, require_approval=False)
                executed.append(result)
            except Exception as exc:
                executed.append({"order": order, "error": str(exc)})

        metrics = self.get_performance_metrics()
        snapshot = self.get_portfolio_snapshot()

        return _safe_json({
            "scenario_name": scenario.get("name"),
            "description": scenario.get("description", ""),
            "trades_executed": len(executed),
            "execution_results": executed,
            "final_portfolio": snapshot,
            "performance": metrics,
        })


# =============================================================================
#  FACTORY FUNCTION
# =============================================================================

def get_trading_engine(
    mode: str = "paper",
    starting_capital: float = 100_000.0,
    **kwargs,
) -> Union[TradingEngine, MockTradingEngine]:
    """
    Factory function to create the appropriate trading engine.

    Parameters:
        mode             : 'paper' (default) or 'mock' returns MockTradingEngine.
                           'live' returns TradingEngine (requires real broker config).
        starting_capital : Initial capital for mock/paper modes.
        **kwargs         : Passed through to the engine constructor.

    Returns:
        TradingEngine or MockTradingEngine instance.

    Usage:
        engine = get_trading_engine(mode="paper", starting_capital=50_000)
        analysis = engine.analyze_stock("AAPL")
        trade = engine.submit_trade({"symbol": "AAPL", "side": "buy", "quantity": 10})
        engine.approve_trade(trade["trade_id"])
    """
    mode_clean = mode.lower().strip()

    if mode_clean in ("paper", "mock"):
        logger.info("Creating MockTradingEngine (paper mode).")
        return MockTradingEngine(
            name=kwargs.get("name", "JARVIS-MockTradingEngine"),
            starting_capital=starting_capital,
            **kwargs,
        )

    if mode_clean == "live":
        logger.warning(
            "Creating LIVE TradingEngine. All trades require explicit approval. "
            "Ensure broker credentials and deposited funds are configured."
        )
        return TradingEngine(
            name=kwargs.get("name", "JARVIS-LiveTradingEngine"),
            mode="live",
            **kwargs,
        )

    logger.warning("Unknown mode '%s' — defaulting to paper.", mode)
    return MockTradingEngine(
        name=kwargs.get("name", "JARVIS-MockTradingEngine"),
        starting_capital=starting_capital,
        **kwargs,
    )


# =============================================================================
#  MODULE SELF-TEST
# =============================================================================

if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(name)s | %(levelname)s | %(message)s")

    print("=" * 70)
    print(" JARVIS BRAINIAC — Trading Engine Self-Test ")
    print("=" * 70)

    # --- Create paper engine ---
    engine = get_trading_engine(mode="paper", starting_capital=100_000)
    print(f"\n1. Engine created: {engine.name} | Mode: {engine.mode}")

    # --- Stock analysis ---
    analysis = engine.analyze_stock("AAPL")
    print(f"\n2. AAPL Analysis:")
    print(f"   Signal : {analysis['signal']}")
    print(f"   Score  : {analysis['composite_score']}")
    print(f"   Price  : ${analysis['price_summary']['current']}")

    # --- Crypto analysis ---
    crypto = engine.analyze_crypto("BTC-USD")
    print(f"\n3. BTC-USD Analysis:")
    print(f"   Signal : {crypto['signal']}")
    print(f"   Vol Regime: {crypto['crypto_specific']['volatility_regime']}")

    # --- Forex analysis ---
    fx = engine.analyze_forex("EURUSD")
    print(f"\n4. EURUSD Analysis:")
    print(f"   Signal : {fx['signal']}")
    print(f"   ATR pips: {fx['technical_indicators']['atr14_pips']}")

    # --- Strategy ---
    strategy = engine.create_strategy("SMA-Crossover", [
        {"type": "entry", "indicator": "sma_crossover", "params": {"short": 20, "long": 50}, "logic": "AND"},
        {"type": "exit", "indicator": "rsi", "params": {"period": 14, "overbought": 70, "oversold": 30}, "logic": "OR"},
    ])
    print(f"\n5. Strategy created: {strategy['name']} (ID: {strategy['strategy_id']})")

    # --- Backtest ---
    data = engine.get_price_history("SPY", period="2y")
    bt = engine.backtest_strategy(strategy, data)
    print(f"\n6. Backtest Results:")
    print(f"   Total Return : {bt['total_return_pct']:.2f}%")
    print(f"   Sharpe       : {bt['sharpe_ratio']:.2f}")
    print(f"   Max Drawdown : {bt['max_drawdown_pct']:.2f}%")
    print(f"   Win Rate     : {bt['win_rate_pct']:.1f}%")

    # --- Risk mgmt ---
    position = engine.calculate_position_size(capital=100_000, risk_percent=0.02, stop_loss=0.05)
    print(f"\n7. Position Size (2% risk, 5% stop): ${position:.2f}")

    var = engine.calculate_var({"AAPL": {"value": 50_000}, "MSFT": {"value": 30_000}}, confidence=0.95)
    print(f"   Portfolio VaR (95%): ${var:.2f}")

    # --- Trade execution ---
    trade = engine.submit_trade({
        "symbol": "AAPL",
        "side": "buy",
        "quantity": 10,
        "order_type": "market",
        "reason": "Test trade — bullish crossover signal.",
    }, require_approval=True)
    print(f"\n8. Trade submitted: {trade['trade_id']} | Status: {trade['status']}")

    # Approve
    approved = engine.approve_trade(trade["trade_id"])
    print(f"   Trade approved & filled @ ${approved.get('fill_price', 0):.2f}")

    # --- Portfolio ---
    snapshot = engine.get_portfolio_snapshot()
    print(f"\n9. Portfolio Snapshot:")
    print(f"   Cash  : ${snapshot['cash']:.2f}")
    print(f"   Equity: ${snapshot['equity']:.2f}")
    print(f"   Return: {snapshot['total_return_pct']:.2f}%")

    # --- Stock screener ---
    screened = engine.screen_stocks({"min_rsi": 20, "max_rsi": 80, "min_price": 50})
    print(f"\n10. Stock Screener: {len(screened)} matches")
    for s in screened[:3]:
        print(f"    {s['symbol']}: score={s['composite_score']:.2f}, signal={s['signal']}")

    # --- Trade history ---
    history = engine.get_trade_history()
    print(f"\n11. Trade History: {len(history)} records")

    # --- Report ---
    report = engine.generate_trade_report()
    print(f"\n12. Trade Report: {report['summary']}")

    print("\n" + "=" * 70)
    print(" All self-tests passed successfully.")
    print("=" * 70)
