# INSTALL_SUPREME.ps1 — Idempotent installer for JARVIS_SUPREME.
# OFFLINE-FIRST · NO API KEYS · OPEN-SOURCE STACK · ALL-PERMISSIONS
# Author: Claude (autonomous build 2026-05-05)
[CmdletBinding()]
param(
  [string]$Canonical = "",
  [string]$Workspace = "",
  [string]$OllamaModel = "llama3",
  [switch]$SkipOllama,
  [switch]$SkipAutostart,
  [switch]$SkipDeps
)

if ([string]::IsNullOrEmpty($Canonical)) { $Canonical = $PSScriptRoot }
if ([string]::IsNullOrEmpty($Workspace)) { $Workspace = $PSScriptRoot }
if ([string]::IsNullOrEmpty($Canonical)) { $Canonical = Get-Location }
if ([string]::IsNullOrEmpty($Workspace)) { $Workspace = Get-Location }

$ErrorActionPreference = "Continue"
$started = Get-Date
$logPath = Join-Path $Workspace "install_supreme_log.txt"
"=== INSTALL_SUPREME start $started ===" | Out-File -FilePath $logPath
function L([string]$m) { $m | Tee-Object -FilePath $logPath -Append }

# ── 1. Pre-flight ────────────────────────────────────────────────────────────
L "[1/8] Pre-flight checks"
if (-not (Test-Path $Canonical)) { L "ERROR: canonical $Canonical missing"; exit 1 }
if (-not (Test-Path $Workspace)) { L "ERROR: workspace $Workspace missing"; exit 1 }
$lock = Join-Path $Canonical ".git\index.lock"
if (Test-Path $lock) { Remove-Item $lock -Force -EA SilentlyContinue; L "  cleared $lock" }

$python = Get-Command python -EA SilentlyContinue
if (-not $python) {
    $localPy = Join-Path $env:LOCALAPPDATA "Programs\Python"
    if (Test-Path $localPy) {
        $exe = Get-ChildItem -Path $localPy -Filter "python.exe" -Recurse -File -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($exe) {
            $pyDir = Split-Path $exe.FullName
            $env:PATH = "$pyDir;$pyDir\Scripts;$env:PATH"
            $python = Get-Command python -EA SilentlyContinue
            L "  auto-detected python at $($exe.FullName)"
        }
    }
}

if (-not $python) { L "ERROR: python not on PATH"; exit 2 }
L "  python: $($python.Source)"

# ── 2. Venv ──────────────────────────────────────────────────────────────────
L "[2/8] Venv"
$venvPath = Join-Path $Canonical ".venv"
$activate = Join-Path $venvPath "Scripts\Activate.ps1"
if (-not (Test-Path $activate)) {
  L "  creating venv at $venvPath"
  python -m venv $venvPath
}
& $activate
L "  venv active: $env:VIRTUAL_ENV"

# ── 3. Pip deps (open-source only) ───────────────────────────────────────────
if (-not $SkipDeps) {
  L "[3/8] Pip deps (open-source only)"
  python -m pip install --quiet --upgrade pip setuptools wheel 2>&1 | Out-Null
  $deps = @(
    "pytest", "pytest-asyncio",
    "fastapi", "uvicorn", "httpx", "pydantic",
    "flask", "requests", "click", "rich",
    "numpy", "scipy", "pandas",
    "pillow", "matplotlib",
    "PyYAML", "toml", "python-dotenv",
    "psutil", "watchdog",
    "sentence-transformers",          # offline embeddings
    "llama-cpp-python",                # offline LLM (cpu fallback)
    "ollama",                          # python client
    "duckdb",                          # local OLAP
    "chromadb",                        # local vector DB
    "networkx",                        # graph
    "rapidfuzz"                        # fuzzy match
  )
  foreach ($d in $deps) {
    L "  pip install $d"
    python -m pip install --quiet $d 2>&1 | Tee-Object -FilePath $logPath -Append | Out-Null
  }
  if (Test-Path (Join-Path $Canonical "runtime\setup.py")) {
    L "  pip install -e runtime"
    python -m pip install -e (Join-Path $Canonical "runtime") --quiet 2>&1 | Out-Null
  }
} else { L "[3/8] Skipped pip deps" }

# ── 4. Ollama (local LLM, free, open-source) ─────────────────────────────────
if (-not $SkipOllama) {
  L "[4/8] Ollama (offline LLM)"
  $ollama = Get-Command ollama -EA SilentlyContinue
  if (-not $ollama) {
    L "  Ollama not installed. Download: https://ollama.com/download/windows"
    L "  After install, re-run with -SkipOllama:`$false"
  } else {
    L "  ollama: $($ollama.Source)"
    L "  pulling $OllamaModel (background)..."
    Start-Job -ScriptBlock { param($m) ollama pull $m } -ArgumentList $OllamaModel | Out-Null
  }
} else { L "[4/8] Skipped Ollama" }

# ── 5. Permissions config ────────────────────────────────────────────────────
L "[5/8] Permissions config"
$envFile = Join-Path $Canonical ".env.supreme"
@"
# JARVIS_SUPREME runtime config — generated by INSTALL_SUPREME.ps1
OFFLINE_MODE=1
ALLOW_ALL=1
JARVIS_PERM_LEVEL=GOD
JARVIS_REQUIRE_API_KEYS=0
JARVIS_LOCAL_LLM_PRIORITY=ollama,llamacpp,transformers
OLLAMA_HOST=http://127.0.0.1:11434
OLLAMA_MODEL=$OllamaModel
PYTHONUTF8=1
AGENCY_ROOT=$Canonical
"@ | Out-File -FilePath $envFile -Encoding utf8
L "  wrote $envFile"

# ── 6. Autostart entry ───────────────────────────────────────────────────────
if (-not $SkipAutostart) {
  L "[6/8] Autostart"
  $startup = [Environment]::GetFolderPath("Startup")
  $shortcut = Join-Path $startup "JARVIS_SUPREME.lnk"
  $launcher = Join-Path $Workspace "JARVIS_SUPREME.ps1"
  $shell = New-Object -ComObject WScript.Shell
  $sc = $shell.CreateShortcut($shortcut)
  $sc.TargetPath = "powershell.exe"
  $sc.Arguments = "-ExecutionPolicy Bypass -WindowStyle Hidden -File `"$launcher`" -Cmd run"
  $sc.WorkingDirectory = $Workspace
  $sc.Description = "JARVIS_SUPREME autostart"
  $sc.Save()
  L "  wrote $shortcut"

  # Schtasks for continuous-improvement loop
  schtasks /Query /TN "JARVIS_continuous_improvement" 2>$null | Out-Null
  if ($LASTEXITCODE -ne 0) {
    $action = "powershell.exe -ExecutionPolicy Bypass -File `"$launcher`" -Cmd selftest"
    schtasks /Create /SC HOURLY /MO 4 /TN "JARVIS_continuous_improvement" /TR $action /F 2>&1 | Out-Null
    L "  registered schtasks JARVIS_continuous_improvement (4h)"
  } else { L "  schtasks already registered" }
} else { L "[6/8] Skipped autostart" }

# ── 7. Self-test ─────────────────────────────────────────────────────────────
L "[7/8] Self-test"
$supreme = Join-Path $Workspace "JARVIS_SUPREME.py"
$env:AGENCY_ROOT = $Canonical
$env:OFFLINE_MODE = "1"
$env:ALLOW_ALL = "1"
$env:JARVIS_PERM_LEVEL = "GOD"
python $supreme selftest 2>&1 | Tee-Object -FilePath $logPath -Append
$selftestExit = $LASTEXITCODE
L "  selftest exit_code=$selftestExit"

# ── 8. Summary ───────────────────────────────────────────────────────────────
$elapsed = ((Get-Date) - $started).TotalSeconds
L ""
L "=== INSTALL_SUPREME complete ==="
L "elapsed_s    : $elapsed"
L "selftest     : exit_code=$selftestExit (0=pass)"
L "next         : .\JARVIS_SUPREME.ps1 run"
L "chat         : .\JARVIS_SUPREME.ps1 -Cmd chat"
L "log          : $logPath"

if ($selftestExit -eq 0) {
  Write-Host "✅ INSTALL OK — supreme ready" -ForegroundColor Green
  exit 0
} else {
  Write-Host "⚠️  Install completed with selftest issues — see $logPath" -ForegroundColor Yellow
  exit $selftestExit
}
