#!/usr/bin/env python3
"""
Integration Adapter: computer_use_ootb_bridge.py
=================================================
Bridge interface for the ShowLab "Computer Use OOTB" external repository.

Repo    : https://github.com/showlab/computer_use_ootb
License : Apache-2.0
Purpose : Provides a clean, class-based wrapper around the OOTB GUI agent's
          core ``sampling_loop_sync`` so that upstream orchestrators can
          dispatch desktop-automation tasks without Gradio or manual state
          management.

Architecture overview
---------------------
- ComputerUseOotbBridge   : Main façade (config validation, lifecycle)
- OotbTaskResult          : Structured return value (screenshots, logs, errors)
- _CallbackAggregator     : Collects streaming tool / LLM outputs into the result

Typical usage::

    bridge = ComputerUseOotbBridge(
        planner_model="gpt-4o",
        actor_model="ShowUI",
        openai_api_key=os.environ["OPENAI_API_KEY"],
    )
    result = bridge.execute("Open Chrome and search for 'ootb github'")
    print(result.final_screenshot_b64[:80] + "...")
    bridge.shutdown()
"""

from __future__ import annotations

import base64
import logging
import os
import sys
import threading
import traceback
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logger = logging.getLogger("jarvis.external.computer_use_ootb")
logger.addHandler(logging.NullHandler())

# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class OotbBridgeError(Exception):
    """Base exception for all bridge-level errors."""


class OotbImportError(OotbBridgeError):
    """Raised when the OOTB repository code cannot be imported."""


class OotbConfigError(OotbBridgeError):
    """Raised when bridge configuration is invalid or inconsistent."""


class OotbRuntimeError(OotbBridgeError):
    """Raised when the underlying OOTB loop fails during execution."""


# ---------------------------------------------------------------------------
# Public data types
# ---------------------------------------------------------------------------


class PlannerModel(str, Enum):
    """Supported planner (high-level reasoning) models."""

    CLAUDE_35_SONNET = "claude-3-5-sonnet-20241022"
    GPT_4O = "gpt-4o"
    GPT_4O_MINI = "gpt-4o-mini"
    QWEN2_VL_MAX = "qwen2-vl-max"
    QWEN2_VL_2B_LOCAL = "qwen2-vl-2b-instruct"
    QWEN2_VL_7B_LOCAL = "qwen2-vl-7b-instruct"
    QWEN25_VL_3B_LOCAL = "qwen2.5-vl-3b-instruct"
    QWEN25_VL_7B_LOCAL = "qwen2.5-vl-7b-instruct"
    QWEN2_VL_2B_SSH = "qwen2-vl-2b (ssh)"
    QWEN2_VL_7B_SSH = "qwen2-vl-7b (ssh)"


class ActorModel(str, Enum):
    """Supported actor (low-level UI action) models."""

    SHOWUI = "ShowUI"
    UI_TARS = "UI-TARS"
    CLAUDE = "claude"  # unified planner+actor via Anthropic Computer Use


@dataclass
class OotbTaskResult:
    """Structured result returned by ``ComputerUseOotbBridge.execute``.

    Attributes
    ----------
    success : bool
        True if the loop terminated without an unhandled exception.
    message_history : list[dict]
        Complete message transcript (system, user, assistant, tool) in
        Anthropic BetaMessageParam-compatible dict form.
    tool_outputs : list[dict]
        Chronological list of every tool invocation and its result.
    llm_outputs : list[str]
        Text generated by the planner / actor at each turn.
    final_screenshot_b64 : str | None
        Base64-encoded PNG of the last screenshot captured, if any.
    error : str | None
        Human-readable error description when ``success`` is False.
    metadata : dict
        Arbitrary key/value pairs for observability (timings, token counts, etc.).
    """

    success: bool = False
    message_history: List[Dict[str, Any]] = field(default_factory=list)
    tool_outputs: List[Dict[str, Any]] = field(default_factory=list)
    llm_outputs: List[str] = field(default_factory=list)
    final_screenshot_b64: Optional[str] = None
    error: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


@dataclass
class _StreamBuffer:
    """Thread-safe accumulator for callbacks fired by the OOTB loop."""

    tool_outputs: List[Dict[str, Any]] = field(default_factory=list)
    llm_outputs: List[str] = field(default_factory=list)
    last_screenshot_b64: Optional[str] = None
    _lock: threading.Lock = field(default_factory=threading.Lock)

    def on_tool_output(self, result: Any, tool_id: str) -> None:
        """Called by OOTB whenever a tool finishes."""
        entry: Dict[str, Any] = {"tool_id": tool_id, "timestamp": _now_iso()}
        # result is expected to be a ToolResult-like object
        if hasattr(result, "output"):
            entry["output"] = result.output
        if hasattr(result, "error"):
            entry["error"] = result.error
        if hasattr(result, "base64_image") and result.base64_image:
            entry["has_image"] = True
            self.last_screenshot_b64 = result.base64_image
        if hasattr(result, "system"):
            entry["system"] = result.system
        with self._lock:
            self.tool_outputs.append(entry)

    def on_llm_output(self, block: Any) -> None:
        """Called by OOTB whenever the LLM emits a content block."""
        text = ""
        if hasattr(block, "text"):
            text = block.text
        elif isinstance(block, dict):
            text = block.get("text", "")
        with self._lock:
            if text:
                self.llm_outputs.append(text)

    def on_api_response(self, response: Any) -> None:
        """Called by OOTB after each API round-trip (optional telemetry)."""
        # Intentionally no-op for now; could record token usage here.
        pass


def _now_iso() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).isoformat()


def _resolve_ootb_path(extra_search_paths: Optional[List[str]] = None) -> Optional[Path]:
    """Locate the OOTB repository on disk.

    Resolution order:
    1. ``COMPUTER_USE_OOTB_ROOT`` environment variable.
    2. ``extra_search_paths`` (caller-provided list).
    3. Common relative locations from this bridge file.
    4. Python path scanning for ``computer_use_demo``.
    """
    env_root = os.environ.get("COMPUTER_USE_OOTB_ROOT")
    if env_root:
        p = Path(env_root).expanduser().resolve()
        if (p / "computer_use_demo" / "loop.py").exists():
            return p

    if extra_search_paths:
        for sp in extra_search_paths:
            p = Path(sp).expanduser().resolve()
            if (p / "computer_use_demo" / "loop.py").exists():
                return p

    # Relative to this bridge file: ../../../../../external_repos/computer_use_ootb
    bridge_dir = Path(__file__).resolve().parent
    candidates = [
        bridge_dir / "computer_use_ootb",
        bridge_dir.parent / "computer_use_ootb",
        bridge_dir.parent.parent / "external_repos" / "computer_use_ootb",
        bridge_dir.parent.parent.parent / "external_repos" / "computer_use_ootb",
    ]
    for c in candidates:
        if (c / "computer_use_demo" / "loop.py").exists():
            return c

    # Fallback: see if already importable
    try:
        import computer_use_demo

        return Path(computer_use_demo.__file__).resolve().parent.parent
    except Exception:
        pass

    return None


# ---------------------------------------------------------------------------
# Bridge façade
# ---------------------------------------------------------------------------


class ComputerUseOotbBridge:
    """Production-ready bridge to the ShowLab Computer Use OOTB framework.

    This class handles repository discovery, dependency validation,
    configuration normalisation, and exposes a single ``execute`` method
    that runs the OOTB agent loop to completion.

    Thread-safety
    -------------
    One ``execute`` call at a time per bridge instance.  Create multiple
    instances for concurrent tasks.

    Example
    -------
    .. code-block:: python

        bridge = ComputerUseOotbBridge(
            planner_model=PlannerModel.GPT_4O,
            actor_model=ActorModel.SHOWUI,
            openai_api_key=os.environ["OPENAI_API_KEY"],
            ootb_repo_path="/path/to/computer_use_ootb",
        )
        result = bridge.execute(
            instruction="Open Calculator, compute 1234 * 5678",
            max_iterations=25,
        )
        if result.success:
            print("Done! Last screenshot:", result.final_screenshot_b64[:64])
        else:
            print("Failed:", result.error)
        bridge.shutdown()
    """

    # -- construction -------------------------------------------------------

    def __init__(
        self,
        *,
        planner_model: PlannerModel | str = PlannerModel.GPT_4O,
        actor_model: ActorModel | str = ActorModel.SHOWUI,
        planner_provider: Optional[str] = None,
        actor_provider: Optional[str] = None,
        openai_api_key: Optional[str] = None,
        anthropic_api_key: Optional[str] = None,
        qwen_api_key: Optional[str] = None,
        ootb_repo_path: Optional[str] = None,
        extra_search_paths: Optional[List[str]] = None,
        system_prompt_suffix: str = "",
        showui_max_pixel: Optional[int] = None,
        only_n_most_recent_images: Optional[int] = None,
        max_tokens: int = 4096,
    ) -> None:
        """
        Parameters
        ----------
        planner_model :
            High-level planning model (enum or raw string).
        actor_model :
            Low-level action model (enum or raw string).
        planner_provider :
            Override provider (``anthropic``, ``openai``, ``qwen``, ``ssh``).
            Auto-detected from *planner_model* when ``None``.
        actor_provider :
            Override actor provider.  Auto-detected when ``None``.
        openai_api_key :
            API key for OpenAI models (also read from ``OPENAI_API_KEY`` env).
        anthropic_api_key :
            API key for Anthropic models (also read from ``ANTHROPIC_API_KEY`` env).
        qwen_api_key :
            API key for Qwen models (also read from ``QWEN_API_KEY`` env).
        ootb_repo_path :
            Explicit filesystem path to the cloned OOTB repository.
        extra_search_paths :
            Additional directories to search for the OOTB repo.
        system_prompt_suffix :
            Extra instructions appended to the default system prompt.
        showui_max_pixel :
            Cap the pixel count fed into ShowUI (memory vs. speed trade-off).
        only_n_most_recent_images :
            Limit context window to the *N* most recent screenshots.
        max_tokens :
            Maximum tokens per LLM response.
        """
        self._planner_model = planner_model.value if isinstance(planner_model, Enum) else planner_model
        self._actor_model = actor_model.value if isinstance(actor_model, Enum) else actor_model
        self._system_prompt_suffix = system_prompt_suffix
        self._showui_max_pixel = showui_max_pixel
        self._only_n_most_recent_images = only_n_most_recent_images
        self._max_tokens = max_tokens

        # API keys (explicit > env)
        self._openai_api_key = openai_api_key or os.environ.get("OPENAI_API_KEY", "")
        self._anthropic_api_key = anthropic_api_key or os.environ.get("ANTHROPIC_API_KEY", "")
        self._qwen_api_key = qwen_api_key or os.environ.get("QWEN_API_KEY", "")

        # Resolve OOTB repository location
        self._repo_path = self._resolve_repo(ootb_repo_path, extra_search_paths)
        self._inject_repo_into_path()

        # Lazily-imported OOTB internals (bound after first use)
        self._ootb_loop: Any = None
        self._ootb_api_provider: Any = None
        self._ootb_tool_result: Any = None
        self._api_key_for_loop: str = ""
        self._provider_for_loop: Any = None

        # Provider auto-detection
        self._planner_provider = planner_provider or self._auto_detect_provider(self._planner_model)
        self._actor_provider = actor_provider or self._auto_detect_provider(self._actor_model)

        # Validate configuration early
        self._validate_config()

        logger.info(
            "ComputerUseOotbBridge initialised (planner=%s/%s, actor=%s/%s, repo=%s)",
            self._planner_model,
            self._planner_provider,
            self._actor_model,
            self._actor_provider,
            self._repo_path,
        )

    # -- internal helpers ---------------------------------------------------

    def _resolve_repo(self, explicit: Optional[str], extras: Optional[List[str]]) -> Path:
        if explicit:
            p = Path(explicit).expanduser().resolve()
            if not (p / "computer_use_demo" / "loop.py").exists():
                raise OotbConfigError(
                    f"Explicit OOTB repo path does not contain expected code: {p}"
                )
            return p

        found = _resolve_ootb_path(extras)
        if found is None:
            raise OotbImportError(
                "Cannot locate the computer_use_ootb repository. "
                "Clone it from https://github.com/showlab/computer_use_ootb and either:\n"
                "  1. Set COMPUTER_USE_OOTB_ROOT env var, or\n"
                "  2. Pass ootb_repo_path=..., or\n"
                "  3. Place it under external_repos/computer_use_ootb relative to this bridge."
            )
        return found

    def _inject_repo_into_path(self) -> None:
        repo_str = str(self._repo_path)
        if repo_str not in sys.path:
            sys.path.insert(0, repo_str)
            logger.debug("Injected OOTB repo into sys.path: %s", repo_str)

    def _auto_detect_provider(self, model: str) -> str:
        model_l = model.lower()
        if "claude" in model_l:
            return "anthropic"
        if "gpt" in model_l or model_l.startswith("openai"):
            return "openai"
        if "qwen" in model_l:
            if "(ssh)" in model:
                return "ssh"
            return "qwen" if "max" in model_l else "qwen"  # local or API
        if "showui" in model_l or "ui-tars" in model_l:
            return "local"
        return "openai"  # safest fallback

    def _validate_config(self) -> None:
        # Planner key check
        if self._planner_provider == "anthropic" and not self._anthropic_api_key:
            raise OotbConfigError("Anthropic planner selected but ANTHROPIC_API_KEY is empty.")
        if self._planner_provider == "openai" and not self._openai_api_key:
            raise OotbConfigError("OpenAI planner selected but OPENAI_API_KEY is empty.")
        if self._planner_provider == "qwen" and not self._qwen_api_key:
            # Allow empty for local Qwen?  Warn only.
            if "max" in self._planner_model.lower():
                raise OotbConfigError("Qwen API planner selected but QWEN_API_KEY is empty.")

    def _ensure_imports(self) -> None:
        """Idempotent lazy import of OOTB internals."""
        if self._ootb_loop is not None:
            return
        try:
            from computer_use_demo.loop import APIProvider, sampling_loop_sync
            from computer_use_demo.tools import ToolResult

            self._ootb_loop = sampling_loop_sync
            self._ootb_api_provider = APIProvider
            self._ootb_tool_result = ToolResult
        except Exception as exc:
            raise OotbImportError(
                f"Failed to import OOTB internals from {self._repo_path}: {exc}"
            ) from exc

        # Map string provider -> enum value
        provider_map = {
            "anthropic": self._ootb_api_provider.ANTHROPIC,
            "bedrock": self._ootb_api_provider.BEDROCK,
            "vertex": self._ootb_api_provider.VERTEX,
            "openai": self._ootb_api_provider.OPENAI,
            "qwen": self._ootb_api_provider.QWEN,
            "ssh": self._ootb_api_provider.SSH,
            "local": None,  # local models don't use APIProvider
        }

        # Determine which provider & API key drive the loop
        # OOTB's loop.py expects a single *api_provider* and *api_key*.
        # For planner-actor split, the loop internally re-routes.
        self._provider_for_loop = provider_map.get(self._planner_provider)

        # API key selection
        if self._planner_provider == "anthropic":
            self._api_key_for_loop = self._anthropic_api_key
        elif self._planner_provider == "openai":
            self._api_key_for_loop = self._openai_api_key
        elif self._planner_provider in ("qwen", "ssh"):
            self._api_key_for_loop = self._qwen_api_key or ""
        else:
            self._api_key_for_loop = self._openai_api_key or self._anthropic_api_key or ""

    # -- public API ---------------------------------------------------------

    def execute(
        self,
        instruction: str,
        *,
        max_iterations: int = 50,
        timeout_seconds: Optional[float] = None,
        callbacks: Optional[Dict[str, Callable]] = None,
    ) -> OotbTaskResult:
        """Run a single desktop-automation task to completion.

        Parameters
        ----------
        instruction :
            Natural-language description of the task, e.g.
            ``"Open VS Code and create a new file called hello.py"``.
        max_iterations :
            Hard cap on the number of thinking-acting turns.  Prevents
            infinite loops when the model gets stuck.
        timeout_seconds :
            Wall-clock timeout (not strictly enforced by this wrapper yet,
            but forwarded to ``metadata`` for upstream schedulers).
        callbacks :
            Optional dict with keys ``tool_output``, ``llm_output``,
            ``api_response`` mapping to callables with the same signatures
            as the private callback methods in ``_StreamBuffer``.

        Returns
        -------
        OotbTaskResult
            Structured result including full message history, tool log,
            LLM transcript, and final screenshot.
        """
        self._ensure_imports()

        buf = _StreamBuffer()
        result = OotbTaskResult(metadata={"instruction": instruction})

        # Build initial message
        messages: List[Any] = [
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": instruction},
                ],
            }
        ]

        # Prepare OOTB-compatible callbacks
        tool_cb = callbacks.get("tool_output") if callbacks else None
        llm_cb = callbacks.get("llm_output") if callbacks else None
        api_cb = callbacks.get("api_response") if callbacks else None

        def _tool_output_wrapper(res: Any, tool_id: str) -> None:
            buf.on_tool_output(res, tool_id)
            if tool_cb:
                tool_cb(res, tool_id)

        def _output_wrapper(block: Any) -> None:
            buf.on_llm_output(block)
            if llm_cb:
                llm_cb(block)

        def _api_resp_wrapper(resp: Any) -> None:
            buf.on_api_response(resp)
            if api_cb:
                api_cb(resp)

        try:
            # OOTB's loop returns the updated message history
            history = self._ootb_loop(
                planner_model=self._planner_model,
                planner_provider=self._provider_for_loop,
                actor_model=self._actor_model,
                actor_provider=None,  # OOTB infers from actor_model string
                system_prompt_suffix=self._system_prompt_suffix,
                messages=messages,
                output_callback=_output_wrapper,
                tool_output_callback=_tool_output_wrapper,
                tool_result_callback=lambda r: None,  # already handled by tool_output
                api_response_callback=_api_resp_wrapper,
                api_key=self._api_key_for_loop,
                only_n_most_recent_images=self._only_n_most_recent_images,
                max_tokens=self._max_tokens,
            )

            result.success = True
            result.message_history = self._serialise_history(history)
            result.tool_outputs = buf.tool_outputs
            result.llm_outputs = buf.llm_outputs
            result.final_screenshot_b64 = buf.last_screenshot_b64
            result.metadata.update(
                {
                    "turns": len(buf.llm_outputs),
                    "tool_calls": len(buf.tool_outputs),
                    "planner": self._planner_model,
                    "actor": self._actor_model,
                }
            )
        except Exception as exc:
            logger.error("OOTB loop failed: %s", exc, exc_info=True)
            result.success = False
            result.error = f"{type(exc).__name__}: {exc}"
            result.metadata["traceback"] = traceback.format_exc()

        return result

    def shutdown(self) -> None:
        """Release any retained resources.

        Currently a no-op because OOTB is stateless between tasks, but
        calling this is recommended for forward compatibility.
        """
        logger.info("ComputerUseOotbBridge shutdown (noop).")

    # -- serialisation helpers ----------------------------------------------

    @staticmethod
    def _serialise_history(history: Any) -> List[Dict[str, Any]]:
        """Convert OOTB BetaMessageParam list to plain dicts for JSON serialisation."""
        try:
            import json

            # Best-effort: if already dict-like, return as-is
            if isinstance(history, list):
                return [
                    dict(msg) if not isinstance(msg, dict) else msg for msg in history
                ]
        except Exception:
            pass
        return []

    # -- property accessors -------------------------------------------------

    @property
    def repo_path(self) -> Path:
        """Filesystem path to the discovered OOTB repository."""
        return self._repo_path

    @property
    def planner_model(self) -> str:
        return self._planner_model

    @property
    def actor_model(self) -> str:
        return self._actor_model


# ---------------------------------------------------------------------------
# Convenience factory
# ---------------------------------------------------------------------------


def create_bridge_from_env(
    planner_model: PlannerModel | str = PlannerModel.GPT_4O,
    actor_model: ActorModel | str = ActorModel.SHOWUI,
    **override_kwargs: Any,
) -> ComputerUseOotbBridge:
    """Create a bridge reading all API keys from environment variables.

    Expected env vars::

        OPENAI_API_KEY      # required for GPT-4o planner
        ANTHROPIC_API_KEY   # required for Claude planner
        QWEN_API_KEY        # required for Qwen planner
        COMPUTER_USE_OOTB_ROOT  # optional, repo location

    All other ``**override_kwargs`` are forwarded to the bridge constructor.
    """
    return ComputerUseOotbBridge(
        planner_model=planner_model,
        actor_model=actor_model,
        **override_kwargs,
    )


# ---------------------------------------------------------------------------
# CLI smoke-test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Smoke-test the OOTB bridge")
    parser.add_argument("instruction", help="Task description")
    parser.add_argument("--planner", default="gpt-4o")
    parser.add_argument("--actor", default="ShowUI")
    parser.add_argument("--repo", default=None, help="Path to OOTB repo")
    parser.add_argument("--max-iter", type=int, default=20)
    parser.add_argument("--verbose", action="store_true")
    args = parser.parse_args()

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(name)s] %(levelname)s %(message)s",
    )

    bridge = ComputerUseOotbBridge(
        planner_model=args.planner,
        actor_model=args.actor,
        ootb_repo_path=args.repo,
    )
    print(f"[BRIDGE] repo={bridge.repo_path}")
    print(f"[BRIDGE] planner={bridge.planner_model}  actor={bridge.actor_model}")
    print(f"[BRIDGE] executing: {args.instruction!r}")

    res = bridge.execute(args.instruction, max_iterations=args.max_iter)
    print(f"[BRIDGE] success={res.success}")
    print(f"[BRIDGE] turns={res.metadata.get('turns')}  tool_calls={res.metadata.get('tool_calls')}")
    if res.error:
        print(f"[BRIDGE] ERROR: {res.error}")
    if res.final_screenshot_b64:
        print(f"[BRIDGE] final screenshot (base64, len={len(res.final_screenshot_b64)})")
    bridge.shutdown()
